## Generated by tools/generate_stubs.py. Do not edit manually.

type
  ServiceModuleCount* = object
    module*: string
    functionCount*: int

let ServiceModuleCounts*: seq[ServiceModuleCount] = @[
  ServiceModuleCount(module: "account_data", functionCount: 11),
  ServiceModuleCount(module: "admin", functionCount: 48),
  ServiceModuleCount(module: "appservice", functionCount: 25),
  ServiceModuleCount(module: "client", functionCount: 8),
  ServiceModuleCount(module: "config", functionCount: 6),
  ServiceModuleCount(module: "deactivate", functionCount: 3),
  ServiceModuleCount(module: "emergency", functionCount: 4),
  ServiceModuleCount(module: "federation", functionCount: 14),
  ServiceModuleCount(module: "globals", functionCount: 18),
  ServiceModuleCount(module: "key_backups", functionCount: 17),
  ServiceModuleCount(module: "manager.rs", functionCount: 7),
  ServiceModuleCount(module: "media", functionCount: 77),
  ServiceModuleCount(module: "membership", functionCount: 19),
  ServiceModuleCount(module: "migrations.rs", functionCount: 8),
  ServiceModuleCount(module: "mod.rs", functionCount: 0),
  ServiceModuleCount(module: "oauth", functionCount: 40),
  ServiceModuleCount(module: "once_services.rs", functionCount: 1),
  ServiceModuleCount(module: "presence", functionCount: 30),
  ServiceModuleCount(module: "pusher", functionCount: 29),
  ServiceModuleCount(module: "registration_tokens", functionCount: 16),
  ServiceModuleCount(module: "resolver", functionCount: 54),
  ServiceModuleCount(module: "rooms", functionCount: 349),
  ServiceModuleCount(module: "sending", functionCount: 47),
  ServiceModuleCount(module: "server_keys", functionCount: 42),
  ServiceModuleCount(module: "service.rs", functionCount: 7),
  ServiceModuleCount(module: "services.rs", functionCount: 7),
  ServiceModuleCount(module: "sync", functionCount: 28),
  ServiceModuleCount(module: "transaction_ids", functionCount: 4),
  ServiceModuleCount(module: "uiaa", functionCount: 8),
  ServiceModuleCount(module: "users", functionCount: 87),
]

const ServiceModuleCountTotal* = 30
