## Generated by tools/generate_stubs.py. Do not edit manually.

type
  DatabaseColumnFamilyDescriptor* = object
    name*: string
    dropped*: bool
    ignored*: bool

let DatabaseColumnFamilyDescriptors*: seq[DatabaseColumnFamilyDescriptor] = @[
]

let RequiredDatabaseColumnFamilies*: seq[string] = @[
]

const DatabaseColumnFamilyDescriptorCount* = 0
const RequiredDatabaseColumnFamilyCount* = 0
