## Generated by tools/generate_stubs.py. Do not edit manually.

import std/[options, tables]

type
  RouteKind* = enum
    rkUnknown
    rkClient
    rkServer
    rkManual

  RouteSpec* = object
    name*: string
    kind*: RouteKind
    requiresAuth*: bool
    federationOnly*: bool

  RouteError* = object
    status*: int
    errcode*: string
    error*: string

  RouteDispatchResult* = object
    routeName*: string
    routeKind*: RouteKind
    requiresAuth*: bool
    federationOnly*: bool
    authorized*: bool
    status*: int
    ok*: bool
    error*: RouteError

  RouteRegistry* = Table[string, RouteSpec]

let PublicClientRouteNames*: seq[string] = @[
  "appservice_ping",
  "check_registration_token_validity",
  "get_login_types_route",
  "get_register_available_route",
  "get_supported_versions_route",
  "login_route",
  "login_token_route",
  "refresh_token_route",
  "register_route",
  "request_3pid_management_token_via_email_route",
  "request_3pid_management_token_via_msisdn_route",
  "sso_callback_route",
  "sso_login_route",
  "sso_login_with_provider_route",
  "third_party_route",
]

let RouteSpecs*: seq[RouteSpec] = @[
  RouteSpec(name: "get_timezone_key_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_profile_field_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_profile_field_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_profile_field_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_timezone_key_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_timezone_key_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "appservice_ping", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "get_supported_versions_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "get_register_available_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "register_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "get_login_types_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "login_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "login_token_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "refresh_token_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "sso_login_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "sso_login_with_provider_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "sso_callback_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "whoami_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "logout_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "logout_all_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "change_password_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "deactivate_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "third_party_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "request_3pid_management_token_via_email_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "request_3pid_management_token_via_msisdn_route", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "check_registration_token_validity", kind: rkClient, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "get_notifications_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_capabilities_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_pushrules_all_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_pushrules_global_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_pushrule_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_pushrule_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_pushrule_enabled_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_pushrule_enabled_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_pushrule_actions_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_pushrule_actions_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_pushrule_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_room_event_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_room_aliases_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_filter_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "create_filter_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "create_openid_token_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_global_account_data_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_room_account_data_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_global_account_data_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_room_account_data_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_displayname_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_displayname_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_avatar_url_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_avatar_url_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_profile_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_presence_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_presence_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "upload_keys_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_keys_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "claim_keys_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "create_backup_version_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "update_backup_version_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_backup_version_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_latest_backup_info_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_backup_info_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "add_backup_keys_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "add_backup_keys_for_room_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "add_backup_keys_for_session_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_backup_keys_for_room_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_backup_keys_for_session_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_backup_keys_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_backup_keys_for_room_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_backup_keys_for_session_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_backup_keys_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_read_marker_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "create_receipt_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "create_typing_event_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "create_room_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "redact_event_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "report_event_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "report_room_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "create_alias_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_alias_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_alias_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "join_room_by_id_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "join_room_by_id_or_alias_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "joined_members_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "knock_room_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "leave_room_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "forget_room_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "joined_rooms_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "kick_user_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "ban_user_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "unban_user_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "invite_user_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_room_visibility_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_room_visibility_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_public_rooms_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_public_rooms_filtered_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "search_users_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_member_events_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_protocols_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "send_message_event_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "send_state_event_for_key_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_state_events_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_state_events_for_key_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "events_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "sync_events_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "sync_events_v5_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_context_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_message_events_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "search_events_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "turn_server_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "send_event_to_device_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "create_content_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_content_thumbnail_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_content_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_content_as_filename_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_media_preview_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_media_config_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_devices_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_device_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "update_device_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_device_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_devices_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "put_dehydrated_device_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_dehydrated_device_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_dehydrated_device_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_dehydrated_events_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_tags_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "update_tag_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "delete_tag_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "upload_signing_keys_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "upload_signatures_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_key_changes_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_pushers_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "set_pushers_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "upgrade_room_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_threads_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_relating_events_with_rel_type_and_event_type_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_relating_events_with_rel_type_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_relating_events_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_transports_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_hierarchy_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_mutual_rooms_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_room_summary", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "well_known_support", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "well_known_client", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "room_initial_sync_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_media_config_legacy_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_media_preview_legacy_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_content_legacy_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_content_as_filename_legacy_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_content_thumbnail_legacy_route", kind: rkClient, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "get_openid_userinfo_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_server_version_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_public_rooms_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_public_rooms_filtered_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "send_transaction_message_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_event_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_backfill_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_missing_events_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_event_authorization_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_room_state_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_room_state_ids_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "create_leave_event_template_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "create_knock_event_template_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "create_leave_event_v1_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "create_leave_event_v2_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "create_knock_event_v1_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "create_join_event_template_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "create_join_event_v1_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "create_join_event_v2_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "create_invite_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_devices_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_room_information_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_profile_information_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_keys_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "claim_keys_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_hierarchy_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "well_known_server", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_content_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "get_content_thumbnail_route", kind: rkServer, requiresAuth: true, federationOnly: true),
  RouteSpec(name: "/_matrix/client/r0/rooms/{room_id}/state/{event_type}", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/client/v3/rooms/{room_id}/state/{event_type}", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/client/r0/rooms/{room_id}/state/{event_type}/", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/client/v3/rooms/{room_id}/state/{event_type}/", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/client/unstable/im.nheko.summary/rooms/{room_id_or_alias}/summary", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_tuwunel/server_version", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/client/server.json", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/key/v2/server", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/key/v2/server/{key_id}", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_tuwunel/local_user_count", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/federation/v1/query/edutypes", kind: rkManual, requiresAuth: false, federationOnly: true),
  RouteSpec(name: "/_matrix/federation/{*path}", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/.well-known/matrix/server", kind: rkManual, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "/_matrix/key/{*path}", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_tuwunel/local_user_count", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/media/v1/config", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/media/v1/upload", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/media/v1/preview_url", kind: rkManual, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "/_matrix/media/v1/download/{server_name}/{media_id}", kind: rkManual, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "/_matrix/media/v1/download/{server_name}/{media_id}/{file_name}", kind: rkManual, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "/_matrix/media/v1/thumbnail/{server_name}/{media_id}", kind: rkManual, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "/_matrix/media/v1/{*path}", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/media/v3/config", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/media/v3/download/{*path}", kind: rkManual, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "/_matrix/media/v3/thumbnail/{*path}", kind: rkManual, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "/_matrix/media/v3/preview_url", kind: rkManual, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "/_matrix/media/r0/config", kind: rkManual, requiresAuth: true, federationOnly: false),
  RouteSpec(name: "/_matrix/media/r0/download/{*path}", kind: rkManual, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "/_matrix/media/r0/thumbnail/{*path}", kind: rkManual, requiresAuth: false, federationOnly: false),
  RouteSpec(name: "/_matrix/media/r0/preview_url", kind: rkManual, requiresAuth: false, federationOnly: false),
]

proc routeRegistry*(): RouteRegistry =
  result = initTable[string, RouteSpec]()
  for spec in RouteSpecs:
    result[spec.name] = spec

proc lookupRoute*(name: string): Option[RouteSpec] =
  for spec in RouteSpecs:
    if spec.name == name:
      return some(spec)
  none(RouteSpec)

proc routeCountByKind*(kind: RouteKind): int =
  result = 0
  for spec in RouteSpecs:
    if spec.kind == kind:
      inc result

proc authorizationState*(spec: RouteSpec; accessTokenPresent, federationAuthenticated: bool): bool =
  if spec.federationOnly:
    return federationAuthenticated
  if spec.requiresAuth:
    return accessTokenPresent
  return true

proc matrixError(status: int; errcode, message: string): RouteError =
  RouteError(status: status, errcode: errcode, error: message)

proc unrecognizedRouteError(routeName: string): RouteError =
  matrixError(404, "M_UNRECOGNIZED", "Unrecognized route: " & routeName)

proc unauthorizedRouteError(spec: RouteSpec): RouteError =
  if spec.federationOnly:
    return matrixError(401, "M_UNAUTHORIZED", "Missing federation authentication")
  matrixError(401, "M_UNAUTHORIZED", "Missing access token authentication")

proc notImplementedRouteError(spec: RouteSpec): RouteError =
  matrixError(501, "M_NOT_YET_IMPLEMENTED", "Route registered but not yet behaviorally ported: " & spec.name)

proc dispatchRoute*(
    routeName: string;
    accessTokenPresent = false;
    federationAuthenticated = false): RouteDispatchResult =
  let specOpt = lookupRoute(routeName)
  if specOpt.isNone:
    let err = unrecognizedRouteError(routeName)
    return RouteDispatchResult(
      routeName: routeName,
      routeKind: rkUnknown,
      requiresAuth: false,
      federationOnly: false,
      authorized: false,
      status: err.status,
      ok: false,
      error: err,
    )

  let spec = specOpt.get
  let authorized = authorizationState(spec, accessTokenPresent, federationAuthenticated)
  if not authorized:
    let err = unauthorizedRouteError(spec)
    return RouteDispatchResult(
      routeName: spec.name,
      routeKind: spec.kind,
      requiresAuth: spec.requiresAuth,
      federationOnly: spec.federationOnly,
      authorized: false,
      status: err.status,
      ok: false,
      error: err,
    )

  let err = notImplementedRouteError(spec)
  RouteDispatchResult(
    routeName: spec.name,
    routeKind: spec.kind,
    requiresAuth: spec.requiresAuth,
    federationOnly: spec.federationOnly,
    authorized: true,
    status: err.status,
    ok: false,
    error: err,
  )

const
  RegisteredRouteCount* = 209
