## Generated by tools/generate_stubs.py. Do not edit manually.

type
  RoutePlaceholder* = object
    routeName*: string

type
  GetTimezoneKeyRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetTimezoneKeyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetProfileFieldRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetProfileFieldRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetProfileFieldRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetProfileFieldRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeleteProfileFieldRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeleteProfileFieldRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetTimezoneKeyRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetTimezoneKeyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeleteTimezoneKeyRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeleteTimezoneKeyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  AppservicePingRequest* = object
    placeholder*: RoutePlaceholder
  AppservicePingResponse* = object
    placeholder*: RoutePlaceholder

type
  GetSupportedVersionsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetSupportedVersionsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRegisterAvailableRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetRegisterAvailableRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  RegisterRouteRequest* = object
    placeholder*: RoutePlaceholder
  RegisterRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetLoginTypesRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetLoginTypesRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  LoginRouteRequest* = object
    placeholder*: RoutePlaceholder
  LoginRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  LoginTokenRouteRequest* = object
    placeholder*: RoutePlaceholder
  LoginTokenRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  RefreshTokenRouteRequest* = object
    placeholder*: RoutePlaceholder
  RefreshTokenRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SsoLoginRouteRequest* = object
    placeholder*: RoutePlaceholder
  SsoLoginRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SsoLoginWithProviderRouteRequest* = object
    placeholder*: RoutePlaceholder
  SsoLoginWithProviderRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SsoCallbackRouteRequest* = object
    placeholder*: RoutePlaceholder
  SsoCallbackRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  WhoamiRouteRequest* = object
    placeholder*: RoutePlaceholder
  WhoamiRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  LogoutRouteRequest* = object
    placeholder*: RoutePlaceholder
  LogoutRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  LogoutAllRouteRequest* = object
    placeholder*: RoutePlaceholder
  LogoutAllRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ChangePasswordRouteRequest* = object
    placeholder*: RoutePlaceholder
  ChangePasswordRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeactivateRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeactivateRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ThirdPartyRouteRequest* = object
    placeholder*: RoutePlaceholder
  ThirdPartyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  Request3pidManagementTokenViaEmailRouteRequest* = object
    placeholder*: RoutePlaceholder
  Request3pidManagementTokenViaEmailRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  Request3pidManagementTokenViaMsisdnRouteRequest* = object
    placeholder*: RoutePlaceholder
  Request3pidManagementTokenViaMsisdnRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CheckRegistrationTokenValidityRequest* = object
    placeholder*: RoutePlaceholder
  CheckRegistrationTokenValidityResponse* = object
    placeholder*: RoutePlaceholder

type
  GetNotificationsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetNotificationsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetCapabilitiesRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetCapabilitiesRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetPushrulesAllRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetPushrulesAllRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetPushrulesGlobalRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetPushrulesGlobalRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetPushruleRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetPushruleRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetPushruleRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetPushruleRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetPushruleEnabledRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetPushruleEnabledRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetPushruleEnabledRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetPushruleEnabledRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetPushruleActionsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetPushruleActionsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetPushruleActionsRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetPushruleActionsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeletePushruleRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeletePushruleRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRoomEventRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetRoomEventRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRoomAliasesRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetRoomAliasesRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetFilterRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetFilterRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateFilterRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateFilterRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateOpenidTokenRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateOpenidTokenRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetGlobalAccountDataRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetGlobalAccountDataRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetRoomAccountDataRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetRoomAccountDataRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetGlobalAccountDataRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetGlobalAccountDataRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRoomAccountDataRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetRoomAccountDataRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetDisplaynameRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetDisplaynameRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetDisplaynameRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetDisplaynameRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetAvatarUrlRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetAvatarUrlRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetAvatarUrlRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetAvatarUrlRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetProfileRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetProfileRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetPresenceRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetPresenceRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetPresenceRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetPresenceRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  UploadKeysRouteRequest* = object
    placeholder*: RoutePlaceholder
  UploadKeysRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetKeysRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetKeysRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ClaimKeysRouteRequest* = object
    placeholder*: RoutePlaceholder
  ClaimKeysRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateBackupVersionRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateBackupVersionRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  UpdateBackupVersionRouteRequest* = object
    placeholder*: RoutePlaceholder
  UpdateBackupVersionRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeleteBackupVersionRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeleteBackupVersionRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetLatestBackupInfoRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetLatestBackupInfoRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetBackupInfoRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetBackupInfoRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  AddBackupKeysRouteRequest* = object
    placeholder*: RoutePlaceholder
  AddBackupKeysRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  AddBackupKeysForRoomRouteRequest* = object
    placeholder*: RoutePlaceholder
  AddBackupKeysForRoomRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  AddBackupKeysForSessionRouteRequest* = object
    placeholder*: RoutePlaceholder
  AddBackupKeysForSessionRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeleteBackupKeysForRoomRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeleteBackupKeysForRoomRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeleteBackupKeysForSessionRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeleteBackupKeysForSessionRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeleteBackupKeysRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeleteBackupKeysRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetBackupKeysForRoomRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetBackupKeysForRoomRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetBackupKeysForSessionRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetBackupKeysForSessionRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetBackupKeysRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetBackupKeysRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetReadMarkerRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetReadMarkerRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateReceiptRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateReceiptRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateTypingEventRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateTypingEventRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateRoomRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateRoomRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  RedactEventRouteRequest* = object
    placeholder*: RoutePlaceholder
  RedactEventRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ReportEventRouteRequest* = object
    placeholder*: RoutePlaceholder
  ReportEventRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ReportRoomRouteRequest* = object
    placeholder*: RoutePlaceholder
  ReportRoomRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateAliasRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateAliasRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeleteAliasRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeleteAliasRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetAliasRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetAliasRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  JoinRoomByIdRouteRequest* = object
    placeholder*: RoutePlaceholder
  JoinRoomByIdRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  JoinRoomByIdOrAliasRouteRequest* = object
    placeholder*: RoutePlaceholder
  JoinRoomByIdOrAliasRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  JoinedMembersRouteRequest* = object
    placeholder*: RoutePlaceholder
  JoinedMembersRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  KnockRoomRouteRequest* = object
    placeholder*: RoutePlaceholder
  KnockRoomRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  LeaveRoomRouteRequest* = object
    placeholder*: RoutePlaceholder
  LeaveRoomRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ForgetRoomRouteRequest* = object
    placeholder*: RoutePlaceholder
  ForgetRoomRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  JoinedRoomsRouteRequest* = object
    placeholder*: RoutePlaceholder
  JoinedRoomsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  KickUserRouteRequest* = object
    placeholder*: RoutePlaceholder
  KickUserRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  BanUserRouteRequest* = object
    placeholder*: RoutePlaceholder
  BanUserRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  UnbanUserRouteRequest* = object
    placeholder*: RoutePlaceholder
  UnbanUserRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  InviteUserRouteRequest* = object
    placeholder*: RoutePlaceholder
  InviteUserRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetRoomVisibilityRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetRoomVisibilityRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRoomVisibilityRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetRoomVisibilityRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetPublicRoomsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetPublicRoomsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetPublicRoomsFilteredRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetPublicRoomsFilteredRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SearchUsersRouteRequest* = object
    placeholder*: RoutePlaceholder
  SearchUsersRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetMemberEventsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetMemberEventsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetProtocolsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetProtocolsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SendMessageEventRouteRequest* = object
    placeholder*: RoutePlaceholder
  SendMessageEventRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SendStateEventForKeyRouteRequest* = object
    placeholder*: RoutePlaceholder
  SendStateEventForKeyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetStateEventsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetStateEventsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetStateEventsForKeyRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetStateEventsForKeyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  EventsRouteRequest* = object
    placeholder*: RoutePlaceholder
  EventsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SyncEventsRouteRequest* = object
    placeholder*: RoutePlaceholder
  SyncEventsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SyncEventsV5RouteRequest* = object
    placeholder*: RoutePlaceholder
  SyncEventsV5RouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetContextRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetContextRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetMessageEventsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetMessageEventsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SearchEventsRouteRequest* = object
    placeholder*: RoutePlaceholder
  SearchEventsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  TurnServerRouteRequest* = object
    placeholder*: RoutePlaceholder
  TurnServerRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SendEventToDeviceRouteRequest* = object
    placeholder*: RoutePlaceholder
  SendEventToDeviceRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateContentRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateContentRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetContentThumbnailRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetContentThumbnailRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetContentRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetContentRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetContentAsFilenameRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetContentAsFilenameRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetMediaPreviewRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetMediaPreviewRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetMediaConfigRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetMediaConfigRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetDevicesRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetDevicesRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetDeviceRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetDeviceRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  UpdateDeviceRouteRequest* = object
    placeholder*: RoutePlaceholder
  UpdateDeviceRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeleteDeviceRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeleteDeviceRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeleteDevicesRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeleteDevicesRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  PutDehydratedDeviceRouteRequest* = object
    placeholder*: RoutePlaceholder
  PutDehydratedDeviceRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeleteDehydratedDeviceRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeleteDehydratedDeviceRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetDehydratedDeviceRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetDehydratedDeviceRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetDehydratedEventsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetDehydratedEventsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetTagsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetTagsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  UpdateTagRouteRequest* = object
    placeholder*: RoutePlaceholder
  UpdateTagRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  DeleteTagRouteRequest* = object
    placeholder*: RoutePlaceholder
  DeleteTagRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  UploadSigningKeysRouteRequest* = object
    placeholder*: RoutePlaceholder
  UploadSigningKeysRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  UploadSignaturesRouteRequest* = object
    placeholder*: RoutePlaceholder
  UploadSignaturesRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetKeyChangesRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetKeyChangesRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetPushersRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetPushersRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SetPushersRouteRequest* = object
    placeholder*: RoutePlaceholder
  SetPushersRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  UpgradeRoomRouteRequest* = object
    placeholder*: RoutePlaceholder
  UpgradeRoomRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetThreadsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetThreadsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRelatingEventsWithRelTypeAndEventTypeRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetRelatingEventsWithRelTypeAndEventTypeRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRelatingEventsWithRelTypeRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetRelatingEventsWithRelTypeRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRelatingEventsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetRelatingEventsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetHierarchyRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetHierarchyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetMutualRoomsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetMutualRoomsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRoomSummaryRequest* = object
    placeholder*: RoutePlaceholder
  GetRoomSummaryResponse* = object
    placeholder*: RoutePlaceholder

type
  WellKnownSupportRequest* = object
    placeholder*: RoutePlaceholder
  WellKnownSupportResponse* = object
    placeholder*: RoutePlaceholder

type
  WellKnownClientRequest* = object
    placeholder*: RoutePlaceholder
  WellKnownClientResponse* = object
    placeholder*: RoutePlaceholder

type
  RoomInitialSyncRouteRequest* = object
    placeholder*: RoutePlaceholder
  RoomInitialSyncRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetMediaConfigLegacyRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetMediaConfigLegacyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetMediaPreviewLegacyRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetMediaPreviewLegacyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetContentLegacyRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetContentLegacyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetContentAsFilenameLegacyRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetContentAsFilenameLegacyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetContentThumbnailLegacyRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetContentThumbnailLegacyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetOpenidUserinfoRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetOpenidUserinfoRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetServerVersionRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetServerVersionRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ServerGetPublicRoomsRouteRequest* = object
    placeholder*: RoutePlaceholder
  ServerGetPublicRoomsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ServerGetPublicRoomsFilteredRouteRequest* = object
    placeholder*: RoutePlaceholder
  ServerGetPublicRoomsFilteredRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  SendTransactionMessageRouteRequest* = object
    placeholder*: RoutePlaceholder
  SendTransactionMessageRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetEventRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetEventRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetBackfillRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetBackfillRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetMissingEventsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetMissingEventsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetEventAuthorizationRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetEventAuthorizationRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRoomStateRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetRoomStateRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRoomStateIdsRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetRoomStateIdsRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateLeaveEventTemplateRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateLeaveEventTemplateRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateKnockEventTemplateRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateKnockEventTemplateRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateLeaveEventV1RouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateLeaveEventV1RouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateLeaveEventV2RouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateLeaveEventV2RouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateKnockEventV1RouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateKnockEventV1RouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateJoinEventTemplateRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateJoinEventTemplateRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateJoinEventV1RouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateJoinEventV1RouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateJoinEventV2RouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateJoinEventV2RouteResponse* = object
    placeholder*: RoutePlaceholder

type
  CreateInviteRouteRequest* = object
    placeholder*: RoutePlaceholder
  CreateInviteRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ServerGetDevicesRouteRequest* = object
    placeholder*: RoutePlaceholder
  ServerGetDevicesRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetRoomInformationRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetRoomInformationRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  GetProfileInformationRouteRequest* = object
    placeholder*: RoutePlaceholder
  GetProfileInformationRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ServerGetKeysRouteRequest* = object
    placeholder*: RoutePlaceholder
  ServerGetKeysRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ServerClaimKeysRouteRequest* = object
    placeholder*: RoutePlaceholder
  ServerClaimKeysRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ServerGetHierarchyRouteRequest* = object
    placeholder*: RoutePlaceholder
  ServerGetHierarchyRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  WellKnownServerRequest* = object
    placeholder*: RoutePlaceholder
  WellKnownServerResponse* = object
    placeholder*: RoutePlaceholder

type
  ServerGetContentRouteRequest* = object
    placeholder*: RoutePlaceholder
  ServerGetContentRouteResponse* = object
    placeholder*: RoutePlaceholder

type
  ServerGetContentThumbnailRouteRequest* = object
    placeholder*: RoutePlaceholder
  ServerGetContentThumbnailRouteResponse* = object
    placeholder*: RoutePlaceholder

proc get_timezone_key_route_placeholder*(req: GetTimezoneKeyRouteRequest): GetTimezoneKeyRouteResponse =
  discard req
  GetTimezoneKeyRouteResponse(placeholder: RoutePlaceholder(routeName: "get_timezone_key_route"))

proc get_profile_field_route_placeholder*(req: GetProfileFieldRouteRequest): GetProfileFieldRouteResponse =
  discard req
  GetProfileFieldRouteResponse(placeholder: RoutePlaceholder(routeName: "get_profile_field_route"))

proc set_profile_field_route_placeholder*(req: SetProfileFieldRouteRequest): SetProfileFieldRouteResponse =
  discard req
  SetProfileFieldRouteResponse(placeholder: RoutePlaceholder(routeName: "set_profile_field_route"))

proc delete_profile_field_route_placeholder*(req: DeleteProfileFieldRouteRequest): DeleteProfileFieldRouteResponse =
  discard req
  DeleteProfileFieldRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_profile_field_route"))

proc set_timezone_key_route_placeholder*(req: SetTimezoneKeyRouteRequest): SetTimezoneKeyRouteResponse =
  discard req
  SetTimezoneKeyRouteResponse(placeholder: RoutePlaceholder(routeName: "set_timezone_key_route"))

proc delete_timezone_key_route_placeholder*(req: DeleteTimezoneKeyRouteRequest): DeleteTimezoneKeyRouteResponse =
  discard req
  DeleteTimezoneKeyRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_timezone_key_route"))

proc appservice_ping_placeholder*(req: AppservicePingRequest): AppservicePingResponse =
  discard req
  AppservicePingResponse(placeholder: RoutePlaceholder(routeName: "appservice_ping"))

proc get_supported_versions_route_placeholder*(req: GetSupportedVersionsRouteRequest): GetSupportedVersionsRouteResponse =
  discard req
  GetSupportedVersionsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_supported_versions_route"))

proc get_register_available_route_placeholder*(req: GetRegisterAvailableRouteRequest): GetRegisterAvailableRouteResponse =
  discard req
  GetRegisterAvailableRouteResponse(placeholder: RoutePlaceholder(routeName: "get_register_available_route"))

proc register_route_placeholder*(req: RegisterRouteRequest): RegisterRouteResponse =
  discard req
  RegisterRouteResponse(placeholder: RoutePlaceholder(routeName: "register_route"))

proc get_login_types_route_placeholder*(req: GetLoginTypesRouteRequest): GetLoginTypesRouteResponse =
  discard req
  GetLoginTypesRouteResponse(placeholder: RoutePlaceholder(routeName: "get_login_types_route"))

proc login_route_placeholder*(req: LoginRouteRequest): LoginRouteResponse =
  discard req
  LoginRouteResponse(placeholder: RoutePlaceholder(routeName: "login_route"))

proc login_token_route_placeholder*(req: LoginTokenRouteRequest): LoginTokenRouteResponse =
  discard req
  LoginTokenRouteResponse(placeholder: RoutePlaceholder(routeName: "login_token_route"))

proc refresh_token_route_placeholder*(req: RefreshTokenRouteRequest): RefreshTokenRouteResponse =
  discard req
  RefreshTokenRouteResponse(placeholder: RoutePlaceholder(routeName: "refresh_token_route"))

proc sso_login_route_placeholder*(req: SsoLoginRouteRequest): SsoLoginRouteResponse =
  discard req
  SsoLoginRouteResponse(placeholder: RoutePlaceholder(routeName: "sso_login_route"))

proc sso_login_with_provider_route_placeholder*(req: SsoLoginWithProviderRouteRequest): SsoLoginWithProviderRouteResponse =
  discard req
  SsoLoginWithProviderRouteResponse(placeholder: RoutePlaceholder(routeName: "sso_login_with_provider_route"))

proc sso_callback_route_placeholder*(req: SsoCallbackRouteRequest): SsoCallbackRouteResponse =
  discard req
  SsoCallbackRouteResponse(placeholder: RoutePlaceholder(routeName: "sso_callback_route"))

proc whoami_route_placeholder*(req: WhoamiRouteRequest): WhoamiRouteResponse =
  discard req
  WhoamiRouteResponse(placeholder: RoutePlaceholder(routeName: "whoami_route"))

proc logout_route_placeholder*(req: LogoutRouteRequest): LogoutRouteResponse =
  discard req
  LogoutRouteResponse(placeholder: RoutePlaceholder(routeName: "logout_route"))

proc logout_all_route_placeholder*(req: LogoutAllRouteRequest): LogoutAllRouteResponse =
  discard req
  LogoutAllRouteResponse(placeholder: RoutePlaceholder(routeName: "logout_all_route"))

proc change_password_route_placeholder*(req: ChangePasswordRouteRequest): ChangePasswordRouteResponse =
  discard req
  ChangePasswordRouteResponse(placeholder: RoutePlaceholder(routeName: "change_password_route"))

proc deactivate_route_placeholder*(req: DeactivateRouteRequest): DeactivateRouteResponse =
  discard req
  DeactivateRouteResponse(placeholder: RoutePlaceholder(routeName: "deactivate_route"))

proc third_party_route_placeholder*(req: ThirdPartyRouteRequest): ThirdPartyRouteResponse =
  discard req
  ThirdPartyRouteResponse(placeholder: RoutePlaceholder(routeName: "third_party_route"))

proc request_3pid_management_token_via_email_route_placeholder*(req: Request3pidManagementTokenViaEmailRouteRequest): Request3pidManagementTokenViaEmailRouteResponse =
  discard req
  Request3pidManagementTokenViaEmailRouteResponse(placeholder: RoutePlaceholder(routeName: "request_3pid_management_token_via_email_route"))

proc request_3pid_management_token_via_msisdn_route_placeholder*(req: Request3pidManagementTokenViaMsisdnRouteRequest): Request3pidManagementTokenViaMsisdnRouteResponse =
  discard req
  Request3pidManagementTokenViaMsisdnRouteResponse(placeholder: RoutePlaceholder(routeName: "request_3pid_management_token_via_msisdn_route"))

proc check_registration_token_validity_placeholder*(req: CheckRegistrationTokenValidityRequest): CheckRegistrationTokenValidityResponse =
  discard req
  CheckRegistrationTokenValidityResponse(placeholder: RoutePlaceholder(routeName: "check_registration_token_validity"))

proc get_notifications_route_placeholder*(req: GetNotificationsRouteRequest): GetNotificationsRouteResponse =
  discard req
  GetNotificationsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_notifications_route"))

proc get_capabilities_route_placeholder*(req: GetCapabilitiesRouteRequest): GetCapabilitiesRouteResponse =
  discard req
  GetCapabilitiesRouteResponse(placeholder: RoutePlaceholder(routeName: "get_capabilities_route"))

proc get_pushrules_all_route_placeholder*(req: GetPushrulesAllRouteRequest): GetPushrulesAllRouteResponse =
  discard req
  GetPushrulesAllRouteResponse(placeholder: RoutePlaceholder(routeName: "get_pushrules_all_route"))

proc get_pushrules_global_route_placeholder*(req: GetPushrulesGlobalRouteRequest): GetPushrulesGlobalRouteResponse =
  discard req
  GetPushrulesGlobalRouteResponse(placeholder: RoutePlaceholder(routeName: "get_pushrules_global_route"))

proc set_pushrule_route_placeholder*(req: SetPushruleRouteRequest): SetPushruleRouteResponse =
  discard req
  SetPushruleRouteResponse(placeholder: RoutePlaceholder(routeName: "set_pushrule_route"))

proc get_pushrule_route_placeholder*(req: GetPushruleRouteRequest): GetPushruleRouteResponse =
  discard req
  GetPushruleRouteResponse(placeholder: RoutePlaceholder(routeName: "get_pushrule_route"))

proc set_pushrule_enabled_route_placeholder*(req: SetPushruleEnabledRouteRequest): SetPushruleEnabledRouteResponse =
  discard req
  SetPushruleEnabledRouteResponse(placeholder: RoutePlaceholder(routeName: "set_pushrule_enabled_route"))

proc get_pushrule_enabled_route_placeholder*(req: GetPushruleEnabledRouteRequest): GetPushruleEnabledRouteResponse =
  discard req
  GetPushruleEnabledRouteResponse(placeholder: RoutePlaceholder(routeName: "get_pushrule_enabled_route"))

proc get_pushrule_actions_route_placeholder*(req: GetPushruleActionsRouteRequest): GetPushruleActionsRouteResponse =
  discard req
  GetPushruleActionsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_pushrule_actions_route"))

proc set_pushrule_actions_route_placeholder*(req: SetPushruleActionsRouteRequest): SetPushruleActionsRouteResponse =
  discard req
  SetPushruleActionsRouteResponse(placeholder: RoutePlaceholder(routeName: "set_pushrule_actions_route"))

proc delete_pushrule_route_placeholder*(req: DeletePushruleRouteRequest): DeletePushruleRouteResponse =
  discard req
  DeletePushruleRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_pushrule_route"))

proc get_room_event_route_placeholder*(req: GetRoomEventRouteRequest): GetRoomEventRouteResponse =
  discard req
  GetRoomEventRouteResponse(placeholder: RoutePlaceholder(routeName: "get_room_event_route"))

proc get_room_aliases_route_placeholder*(req: GetRoomAliasesRouteRequest): GetRoomAliasesRouteResponse =
  discard req
  GetRoomAliasesRouteResponse(placeholder: RoutePlaceholder(routeName: "get_room_aliases_route"))

proc get_filter_route_placeholder*(req: GetFilterRouteRequest): GetFilterRouteResponse =
  discard req
  GetFilterRouteResponse(placeholder: RoutePlaceholder(routeName: "get_filter_route"))

proc create_filter_route_placeholder*(req: CreateFilterRouteRequest): CreateFilterRouteResponse =
  discard req
  CreateFilterRouteResponse(placeholder: RoutePlaceholder(routeName: "create_filter_route"))

proc create_openid_token_route_placeholder*(req: CreateOpenidTokenRouteRequest): CreateOpenidTokenRouteResponse =
  discard req
  CreateOpenidTokenRouteResponse(placeholder: RoutePlaceholder(routeName: "create_openid_token_route"))

proc set_global_account_data_route_placeholder*(req: SetGlobalAccountDataRouteRequest): SetGlobalAccountDataRouteResponse =
  discard req
  SetGlobalAccountDataRouteResponse(placeholder: RoutePlaceholder(routeName: "set_global_account_data_route"))

proc set_room_account_data_route_placeholder*(req: SetRoomAccountDataRouteRequest): SetRoomAccountDataRouteResponse =
  discard req
  SetRoomAccountDataRouteResponse(placeholder: RoutePlaceholder(routeName: "set_room_account_data_route"))

proc get_global_account_data_route_placeholder*(req: GetGlobalAccountDataRouteRequest): GetGlobalAccountDataRouteResponse =
  discard req
  GetGlobalAccountDataRouteResponse(placeholder: RoutePlaceholder(routeName: "get_global_account_data_route"))

proc get_room_account_data_route_placeholder*(req: GetRoomAccountDataRouteRequest): GetRoomAccountDataRouteResponse =
  discard req
  GetRoomAccountDataRouteResponse(placeholder: RoutePlaceholder(routeName: "get_room_account_data_route"))

proc set_displayname_route_placeholder*(req: SetDisplaynameRouteRequest): SetDisplaynameRouteResponse =
  discard req
  SetDisplaynameRouteResponse(placeholder: RoutePlaceholder(routeName: "set_displayname_route"))

proc get_displayname_route_placeholder*(req: GetDisplaynameRouteRequest): GetDisplaynameRouteResponse =
  discard req
  GetDisplaynameRouteResponse(placeholder: RoutePlaceholder(routeName: "get_displayname_route"))

proc set_avatar_url_route_placeholder*(req: SetAvatarUrlRouteRequest): SetAvatarUrlRouteResponse =
  discard req
  SetAvatarUrlRouteResponse(placeholder: RoutePlaceholder(routeName: "set_avatar_url_route"))

proc get_avatar_url_route_placeholder*(req: GetAvatarUrlRouteRequest): GetAvatarUrlRouteResponse =
  discard req
  GetAvatarUrlRouteResponse(placeholder: RoutePlaceholder(routeName: "get_avatar_url_route"))

proc get_profile_route_placeholder*(req: GetProfileRouteRequest): GetProfileRouteResponse =
  discard req
  GetProfileRouteResponse(placeholder: RoutePlaceholder(routeName: "get_profile_route"))

proc set_presence_route_placeholder*(req: SetPresenceRouteRequest): SetPresenceRouteResponse =
  discard req
  SetPresenceRouteResponse(placeholder: RoutePlaceholder(routeName: "set_presence_route"))

proc get_presence_route_placeholder*(req: GetPresenceRouteRequest): GetPresenceRouteResponse =
  discard req
  GetPresenceRouteResponse(placeholder: RoutePlaceholder(routeName: "get_presence_route"))

proc upload_keys_route_placeholder*(req: UploadKeysRouteRequest): UploadKeysRouteResponse =
  discard req
  UploadKeysRouteResponse(placeholder: RoutePlaceholder(routeName: "upload_keys_route"))

proc get_keys_route_placeholder*(req: GetKeysRouteRequest): GetKeysRouteResponse =
  discard req
  GetKeysRouteResponse(placeholder: RoutePlaceholder(routeName: "get_keys_route"))

proc claim_keys_route_placeholder*(req: ClaimKeysRouteRequest): ClaimKeysRouteResponse =
  discard req
  ClaimKeysRouteResponse(placeholder: RoutePlaceholder(routeName: "claim_keys_route"))

proc create_backup_version_route_placeholder*(req: CreateBackupVersionRouteRequest): CreateBackupVersionRouteResponse =
  discard req
  CreateBackupVersionRouteResponse(placeholder: RoutePlaceholder(routeName: "create_backup_version_route"))

proc update_backup_version_route_placeholder*(req: UpdateBackupVersionRouteRequest): UpdateBackupVersionRouteResponse =
  discard req
  UpdateBackupVersionRouteResponse(placeholder: RoutePlaceholder(routeName: "update_backup_version_route"))

proc delete_backup_version_route_placeholder*(req: DeleteBackupVersionRouteRequest): DeleteBackupVersionRouteResponse =
  discard req
  DeleteBackupVersionRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_backup_version_route"))

proc get_latest_backup_info_route_placeholder*(req: GetLatestBackupInfoRouteRequest): GetLatestBackupInfoRouteResponse =
  discard req
  GetLatestBackupInfoRouteResponse(placeholder: RoutePlaceholder(routeName: "get_latest_backup_info_route"))

proc get_backup_info_route_placeholder*(req: GetBackupInfoRouteRequest): GetBackupInfoRouteResponse =
  discard req
  GetBackupInfoRouteResponse(placeholder: RoutePlaceholder(routeName: "get_backup_info_route"))

proc add_backup_keys_route_placeholder*(req: AddBackupKeysRouteRequest): AddBackupKeysRouteResponse =
  discard req
  AddBackupKeysRouteResponse(placeholder: RoutePlaceholder(routeName: "add_backup_keys_route"))

proc add_backup_keys_for_room_route_placeholder*(req: AddBackupKeysForRoomRouteRequest): AddBackupKeysForRoomRouteResponse =
  discard req
  AddBackupKeysForRoomRouteResponse(placeholder: RoutePlaceholder(routeName: "add_backup_keys_for_room_route"))

proc add_backup_keys_for_session_route_placeholder*(req: AddBackupKeysForSessionRouteRequest): AddBackupKeysForSessionRouteResponse =
  discard req
  AddBackupKeysForSessionRouteResponse(placeholder: RoutePlaceholder(routeName: "add_backup_keys_for_session_route"))

proc delete_backup_keys_for_room_route_placeholder*(req: DeleteBackupKeysForRoomRouteRequest): DeleteBackupKeysForRoomRouteResponse =
  discard req
  DeleteBackupKeysForRoomRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_backup_keys_for_room_route"))

proc delete_backup_keys_for_session_route_placeholder*(req: DeleteBackupKeysForSessionRouteRequest): DeleteBackupKeysForSessionRouteResponse =
  discard req
  DeleteBackupKeysForSessionRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_backup_keys_for_session_route"))

proc delete_backup_keys_route_placeholder*(req: DeleteBackupKeysRouteRequest): DeleteBackupKeysRouteResponse =
  discard req
  DeleteBackupKeysRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_backup_keys_route"))

proc get_backup_keys_for_room_route_placeholder*(req: GetBackupKeysForRoomRouteRequest): GetBackupKeysForRoomRouteResponse =
  discard req
  GetBackupKeysForRoomRouteResponse(placeholder: RoutePlaceholder(routeName: "get_backup_keys_for_room_route"))

proc get_backup_keys_for_session_route_placeholder*(req: GetBackupKeysForSessionRouteRequest): GetBackupKeysForSessionRouteResponse =
  discard req
  GetBackupKeysForSessionRouteResponse(placeholder: RoutePlaceholder(routeName: "get_backup_keys_for_session_route"))

proc get_backup_keys_route_placeholder*(req: GetBackupKeysRouteRequest): GetBackupKeysRouteResponse =
  discard req
  GetBackupKeysRouteResponse(placeholder: RoutePlaceholder(routeName: "get_backup_keys_route"))

proc set_read_marker_route_placeholder*(req: SetReadMarkerRouteRequest): SetReadMarkerRouteResponse =
  discard req
  SetReadMarkerRouteResponse(placeholder: RoutePlaceholder(routeName: "set_read_marker_route"))

proc create_receipt_route_placeholder*(req: CreateReceiptRouteRequest): CreateReceiptRouteResponse =
  discard req
  CreateReceiptRouteResponse(placeholder: RoutePlaceholder(routeName: "create_receipt_route"))

proc create_typing_event_route_placeholder*(req: CreateTypingEventRouteRequest): CreateTypingEventRouteResponse =
  discard req
  CreateTypingEventRouteResponse(placeholder: RoutePlaceholder(routeName: "create_typing_event_route"))

proc create_room_route_placeholder*(req: CreateRoomRouteRequest): CreateRoomRouteResponse =
  discard req
  CreateRoomRouteResponse(placeholder: RoutePlaceholder(routeName: "create_room_route"))

proc redact_event_route_placeholder*(req: RedactEventRouteRequest): RedactEventRouteResponse =
  discard req
  RedactEventRouteResponse(placeholder: RoutePlaceholder(routeName: "redact_event_route"))

proc report_event_route_placeholder*(req: ReportEventRouteRequest): ReportEventRouteResponse =
  discard req
  ReportEventRouteResponse(placeholder: RoutePlaceholder(routeName: "report_event_route"))

proc report_room_route_placeholder*(req: ReportRoomRouteRequest): ReportRoomRouteResponse =
  discard req
  ReportRoomRouteResponse(placeholder: RoutePlaceholder(routeName: "report_room_route"))

proc create_alias_route_placeholder*(req: CreateAliasRouteRequest): CreateAliasRouteResponse =
  discard req
  CreateAliasRouteResponse(placeholder: RoutePlaceholder(routeName: "create_alias_route"))

proc delete_alias_route_placeholder*(req: DeleteAliasRouteRequest): DeleteAliasRouteResponse =
  discard req
  DeleteAliasRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_alias_route"))

proc get_alias_route_placeholder*(req: GetAliasRouteRequest): GetAliasRouteResponse =
  discard req
  GetAliasRouteResponse(placeholder: RoutePlaceholder(routeName: "get_alias_route"))

proc join_room_by_id_route_placeholder*(req: JoinRoomByIdRouteRequest): JoinRoomByIdRouteResponse =
  discard req
  JoinRoomByIdRouteResponse(placeholder: RoutePlaceholder(routeName: "join_room_by_id_route"))

proc join_room_by_id_or_alias_route_placeholder*(req: JoinRoomByIdOrAliasRouteRequest): JoinRoomByIdOrAliasRouteResponse =
  discard req
  JoinRoomByIdOrAliasRouteResponse(placeholder: RoutePlaceholder(routeName: "join_room_by_id_or_alias_route"))

proc joined_members_route_placeholder*(req: JoinedMembersRouteRequest): JoinedMembersRouteResponse =
  discard req
  JoinedMembersRouteResponse(placeholder: RoutePlaceholder(routeName: "joined_members_route"))

proc knock_room_route_placeholder*(req: KnockRoomRouteRequest): KnockRoomRouteResponse =
  discard req
  KnockRoomRouteResponse(placeholder: RoutePlaceholder(routeName: "knock_room_route"))

proc leave_room_route_placeholder*(req: LeaveRoomRouteRequest): LeaveRoomRouteResponse =
  discard req
  LeaveRoomRouteResponse(placeholder: RoutePlaceholder(routeName: "leave_room_route"))

proc forget_room_route_placeholder*(req: ForgetRoomRouteRequest): ForgetRoomRouteResponse =
  discard req
  ForgetRoomRouteResponse(placeholder: RoutePlaceholder(routeName: "forget_room_route"))

proc joined_rooms_route_placeholder*(req: JoinedRoomsRouteRequest): JoinedRoomsRouteResponse =
  discard req
  JoinedRoomsRouteResponse(placeholder: RoutePlaceholder(routeName: "joined_rooms_route"))

proc kick_user_route_placeholder*(req: KickUserRouteRequest): KickUserRouteResponse =
  discard req
  KickUserRouteResponse(placeholder: RoutePlaceholder(routeName: "kick_user_route"))

proc ban_user_route_placeholder*(req: BanUserRouteRequest): BanUserRouteResponse =
  discard req
  BanUserRouteResponse(placeholder: RoutePlaceholder(routeName: "ban_user_route"))

proc unban_user_route_placeholder*(req: UnbanUserRouteRequest): UnbanUserRouteResponse =
  discard req
  UnbanUserRouteResponse(placeholder: RoutePlaceholder(routeName: "unban_user_route"))

proc invite_user_route_placeholder*(req: InviteUserRouteRequest): InviteUserRouteResponse =
  discard req
  InviteUserRouteResponse(placeholder: RoutePlaceholder(routeName: "invite_user_route"))

proc set_room_visibility_route_placeholder*(req: SetRoomVisibilityRouteRequest): SetRoomVisibilityRouteResponse =
  discard req
  SetRoomVisibilityRouteResponse(placeholder: RoutePlaceholder(routeName: "set_room_visibility_route"))

proc get_room_visibility_route_placeholder*(req: GetRoomVisibilityRouteRequest): GetRoomVisibilityRouteResponse =
  discard req
  GetRoomVisibilityRouteResponse(placeholder: RoutePlaceholder(routeName: "get_room_visibility_route"))

proc get_public_rooms_route_placeholder*(req: GetPublicRoomsRouteRequest): GetPublicRoomsRouteResponse =
  discard req
  GetPublicRoomsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_public_rooms_route"))

proc get_public_rooms_filtered_route_placeholder*(req: GetPublicRoomsFilteredRouteRequest): GetPublicRoomsFilteredRouteResponse =
  discard req
  GetPublicRoomsFilteredRouteResponse(placeholder: RoutePlaceholder(routeName: "get_public_rooms_filtered_route"))

proc search_users_route_placeholder*(req: SearchUsersRouteRequest): SearchUsersRouteResponse =
  discard req
  SearchUsersRouteResponse(placeholder: RoutePlaceholder(routeName: "search_users_route"))

proc get_member_events_route_placeholder*(req: GetMemberEventsRouteRequest): GetMemberEventsRouteResponse =
  discard req
  GetMemberEventsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_member_events_route"))

proc get_protocols_route_placeholder*(req: GetProtocolsRouteRequest): GetProtocolsRouteResponse =
  discard req
  GetProtocolsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_protocols_route"))

proc send_message_event_route_placeholder*(req: SendMessageEventRouteRequest): SendMessageEventRouteResponse =
  discard req
  SendMessageEventRouteResponse(placeholder: RoutePlaceholder(routeName: "send_message_event_route"))

proc send_state_event_for_key_route_placeholder*(req: SendStateEventForKeyRouteRequest): SendStateEventForKeyRouteResponse =
  discard req
  SendStateEventForKeyRouteResponse(placeholder: RoutePlaceholder(routeName: "send_state_event_for_key_route"))

proc get_state_events_route_placeholder*(req: GetStateEventsRouteRequest): GetStateEventsRouteResponse =
  discard req
  GetStateEventsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_state_events_route"))

proc get_state_events_for_key_route_placeholder*(req: GetStateEventsForKeyRouteRequest): GetStateEventsForKeyRouteResponse =
  discard req
  GetStateEventsForKeyRouteResponse(placeholder: RoutePlaceholder(routeName: "get_state_events_for_key_route"))

proc events_route_placeholder*(req: EventsRouteRequest): EventsRouteResponse =
  discard req
  EventsRouteResponse(placeholder: RoutePlaceholder(routeName: "events_route"))

proc sync_events_route_placeholder*(req: SyncEventsRouteRequest): SyncEventsRouteResponse =
  discard req
  SyncEventsRouteResponse(placeholder: RoutePlaceholder(routeName: "sync_events_route"))

proc sync_events_v5_route_placeholder*(req: SyncEventsV5RouteRequest): SyncEventsV5RouteResponse =
  discard req
  SyncEventsV5RouteResponse(placeholder: RoutePlaceholder(routeName: "sync_events_v5_route"))

proc get_context_route_placeholder*(req: GetContextRouteRequest): GetContextRouteResponse =
  discard req
  GetContextRouteResponse(placeholder: RoutePlaceholder(routeName: "get_context_route"))

proc get_message_events_route_placeholder*(req: GetMessageEventsRouteRequest): GetMessageEventsRouteResponse =
  discard req
  GetMessageEventsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_message_events_route"))

proc search_events_route_placeholder*(req: SearchEventsRouteRequest): SearchEventsRouteResponse =
  discard req
  SearchEventsRouteResponse(placeholder: RoutePlaceholder(routeName: "search_events_route"))

proc turn_server_route_placeholder*(req: TurnServerRouteRequest): TurnServerRouteResponse =
  discard req
  TurnServerRouteResponse(placeholder: RoutePlaceholder(routeName: "turn_server_route"))

proc send_event_to_device_route_placeholder*(req: SendEventToDeviceRouteRequest): SendEventToDeviceRouteResponse =
  discard req
  SendEventToDeviceRouteResponse(placeholder: RoutePlaceholder(routeName: "send_event_to_device_route"))

proc create_content_route_placeholder*(req: CreateContentRouteRequest): CreateContentRouteResponse =
  discard req
  CreateContentRouteResponse(placeholder: RoutePlaceholder(routeName: "create_content_route"))

proc get_content_thumbnail_route_placeholder*(req: GetContentThumbnailRouteRequest): GetContentThumbnailRouteResponse =
  discard req
  GetContentThumbnailRouteResponse(placeholder: RoutePlaceholder(routeName: "get_content_thumbnail_route"))

proc get_content_route_placeholder*(req: GetContentRouteRequest): GetContentRouteResponse =
  discard req
  GetContentRouteResponse(placeholder: RoutePlaceholder(routeName: "get_content_route"))

proc get_content_as_filename_route_placeholder*(req: GetContentAsFilenameRouteRequest): GetContentAsFilenameRouteResponse =
  discard req
  GetContentAsFilenameRouteResponse(placeholder: RoutePlaceholder(routeName: "get_content_as_filename_route"))

proc get_media_preview_route_placeholder*(req: GetMediaPreviewRouteRequest): GetMediaPreviewRouteResponse =
  discard req
  GetMediaPreviewRouteResponse(placeholder: RoutePlaceholder(routeName: "get_media_preview_route"))

proc get_media_config_route_placeholder*(req: GetMediaConfigRouteRequest): GetMediaConfigRouteResponse =
  discard req
  GetMediaConfigRouteResponse(placeholder: RoutePlaceholder(routeName: "get_media_config_route"))

proc get_devices_route_placeholder*(req: GetDevicesRouteRequest): GetDevicesRouteResponse =
  discard req
  GetDevicesRouteResponse(placeholder: RoutePlaceholder(routeName: "get_devices_route"))

proc get_device_route_placeholder*(req: GetDeviceRouteRequest): GetDeviceRouteResponse =
  discard req
  GetDeviceRouteResponse(placeholder: RoutePlaceholder(routeName: "get_device_route"))

proc update_device_route_placeholder*(req: UpdateDeviceRouteRequest): UpdateDeviceRouteResponse =
  discard req
  UpdateDeviceRouteResponse(placeholder: RoutePlaceholder(routeName: "update_device_route"))

proc delete_device_route_placeholder*(req: DeleteDeviceRouteRequest): DeleteDeviceRouteResponse =
  discard req
  DeleteDeviceRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_device_route"))

proc delete_devices_route_placeholder*(req: DeleteDevicesRouteRequest): DeleteDevicesRouteResponse =
  discard req
  DeleteDevicesRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_devices_route"))

proc put_dehydrated_device_route_placeholder*(req: PutDehydratedDeviceRouteRequest): PutDehydratedDeviceRouteResponse =
  discard req
  PutDehydratedDeviceRouteResponse(placeholder: RoutePlaceholder(routeName: "put_dehydrated_device_route"))

proc delete_dehydrated_device_route_placeholder*(req: DeleteDehydratedDeviceRouteRequest): DeleteDehydratedDeviceRouteResponse =
  discard req
  DeleteDehydratedDeviceRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_dehydrated_device_route"))

proc get_dehydrated_device_route_placeholder*(req: GetDehydratedDeviceRouteRequest): GetDehydratedDeviceRouteResponse =
  discard req
  GetDehydratedDeviceRouteResponse(placeholder: RoutePlaceholder(routeName: "get_dehydrated_device_route"))

proc get_dehydrated_events_route_placeholder*(req: GetDehydratedEventsRouteRequest): GetDehydratedEventsRouteResponse =
  discard req
  GetDehydratedEventsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_dehydrated_events_route"))

proc get_tags_route_placeholder*(req: GetTagsRouteRequest): GetTagsRouteResponse =
  discard req
  GetTagsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_tags_route"))

proc update_tag_route_placeholder*(req: UpdateTagRouteRequest): UpdateTagRouteResponse =
  discard req
  UpdateTagRouteResponse(placeholder: RoutePlaceholder(routeName: "update_tag_route"))

proc delete_tag_route_placeholder*(req: DeleteTagRouteRequest): DeleteTagRouteResponse =
  discard req
  DeleteTagRouteResponse(placeholder: RoutePlaceholder(routeName: "delete_tag_route"))

proc upload_signing_keys_route_placeholder*(req: UploadSigningKeysRouteRequest): UploadSigningKeysRouteResponse =
  discard req
  UploadSigningKeysRouteResponse(placeholder: RoutePlaceholder(routeName: "upload_signing_keys_route"))

proc upload_signatures_route_placeholder*(req: UploadSignaturesRouteRequest): UploadSignaturesRouteResponse =
  discard req
  UploadSignaturesRouteResponse(placeholder: RoutePlaceholder(routeName: "upload_signatures_route"))

proc get_key_changes_route_placeholder*(req: GetKeyChangesRouteRequest): GetKeyChangesRouteResponse =
  discard req
  GetKeyChangesRouteResponse(placeholder: RoutePlaceholder(routeName: "get_key_changes_route"))

proc get_pushers_route_placeholder*(req: GetPushersRouteRequest): GetPushersRouteResponse =
  discard req
  GetPushersRouteResponse(placeholder: RoutePlaceholder(routeName: "get_pushers_route"))

proc set_pushers_route_placeholder*(req: SetPushersRouteRequest): SetPushersRouteResponse =
  discard req
  SetPushersRouteResponse(placeholder: RoutePlaceholder(routeName: "set_pushers_route"))

proc upgrade_room_route_placeholder*(req: UpgradeRoomRouteRequest): UpgradeRoomRouteResponse =
  discard req
  UpgradeRoomRouteResponse(placeholder: RoutePlaceholder(routeName: "upgrade_room_route"))

proc get_threads_route_placeholder*(req: GetThreadsRouteRequest): GetThreadsRouteResponse =
  discard req
  GetThreadsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_threads_route"))

proc get_relating_events_with_rel_type_and_event_type_route_placeholder*(req: GetRelatingEventsWithRelTypeAndEventTypeRouteRequest): GetRelatingEventsWithRelTypeAndEventTypeRouteResponse =
  discard req
  GetRelatingEventsWithRelTypeAndEventTypeRouteResponse(placeholder: RoutePlaceholder(routeName: "get_relating_events_with_rel_type_and_event_type_route"))

proc get_relating_events_with_rel_type_route_placeholder*(req: GetRelatingEventsWithRelTypeRouteRequest): GetRelatingEventsWithRelTypeRouteResponse =
  discard req
  GetRelatingEventsWithRelTypeRouteResponse(placeholder: RoutePlaceholder(routeName: "get_relating_events_with_rel_type_route"))

proc get_relating_events_route_placeholder*(req: GetRelatingEventsRouteRequest): GetRelatingEventsRouteResponse =
  discard req
  GetRelatingEventsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_relating_events_route"))

proc get_hierarchy_route_placeholder*(req: GetHierarchyRouteRequest): GetHierarchyRouteResponse =
  discard req
  GetHierarchyRouteResponse(placeholder: RoutePlaceholder(routeName: "get_hierarchy_route"))

proc get_mutual_rooms_route_placeholder*(req: GetMutualRoomsRouteRequest): GetMutualRoomsRouteResponse =
  discard req
  GetMutualRoomsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_mutual_rooms_route"))

proc get_room_summary_placeholder*(req: GetRoomSummaryRequest): GetRoomSummaryResponse =
  discard req
  GetRoomSummaryResponse(placeholder: RoutePlaceholder(routeName: "get_room_summary"))

proc well_known_support_placeholder*(req: WellKnownSupportRequest): WellKnownSupportResponse =
  discard req
  WellKnownSupportResponse(placeholder: RoutePlaceholder(routeName: "well_known_support"))

proc well_known_client_placeholder*(req: WellKnownClientRequest): WellKnownClientResponse =
  discard req
  WellKnownClientResponse(placeholder: RoutePlaceholder(routeName: "well_known_client"))

proc room_initial_sync_route_placeholder*(req: RoomInitialSyncRouteRequest): RoomInitialSyncRouteResponse =
  discard req
  RoomInitialSyncRouteResponse(placeholder: RoutePlaceholder(routeName: "room_initial_sync_route"))

proc get_media_config_legacy_route_placeholder*(req: GetMediaConfigLegacyRouteRequest): GetMediaConfigLegacyRouteResponse =
  discard req
  GetMediaConfigLegacyRouteResponse(placeholder: RoutePlaceholder(routeName: "get_media_config_legacy_route"))

proc get_media_preview_legacy_route_placeholder*(req: GetMediaPreviewLegacyRouteRequest): GetMediaPreviewLegacyRouteResponse =
  discard req
  GetMediaPreviewLegacyRouteResponse(placeholder: RoutePlaceholder(routeName: "get_media_preview_legacy_route"))

proc get_content_legacy_route_placeholder*(req: GetContentLegacyRouteRequest): GetContentLegacyRouteResponse =
  discard req
  GetContentLegacyRouteResponse(placeholder: RoutePlaceholder(routeName: "get_content_legacy_route"))

proc get_content_as_filename_legacy_route_placeholder*(req: GetContentAsFilenameLegacyRouteRequest): GetContentAsFilenameLegacyRouteResponse =
  discard req
  GetContentAsFilenameLegacyRouteResponse(placeholder: RoutePlaceholder(routeName: "get_content_as_filename_legacy_route"))

proc get_content_thumbnail_legacy_route_placeholder*(req: GetContentThumbnailLegacyRouteRequest): GetContentThumbnailLegacyRouteResponse =
  discard req
  GetContentThumbnailLegacyRouteResponse(placeholder: RoutePlaceholder(routeName: "get_content_thumbnail_legacy_route"))

proc get_openid_userinfo_route_placeholder*(req: GetOpenidUserinfoRouteRequest): GetOpenidUserinfoRouteResponse =
  discard req
  GetOpenidUserinfoRouteResponse(placeholder: RoutePlaceholder(routeName: "get_openid_userinfo_route"))

proc get_server_version_route_placeholder*(req: GetServerVersionRouteRequest): GetServerVersionRouteResponse =
  discard req
  GetServerVersionRouteResponse(placeholder: RoutePlaceholder(routeName: "get_server_version_route"))

proc get_public_rooms_route_placeholder*(req: ServerGetPublicRoomsRouteRequest): ServerGetPublicRoomsRouteResponse =
  discard req
  ServerGetPublicRoomsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_public_rooms_route"))

proc get_public_rooms_filtered_route_placeholder*(req: ServerGetPublicRoomsFilteredRouteRequest): ServerGetPublicRoomsFilteredRouteResponse =
  discard req
  ServerGetPublicRoomsFilteredRouteResponse(placeholder: RoutePlaceholder(routeName: "get_public_rooms_filtered_route"))

proc send_transaction_message_route_placeholder*(req: SendTransactionMessageRouteRequest): SendTransactionMessageRouteResponse =
  discard req
  SendTransactionMessageRouteResponse(placeholder: RoutePlaceholder(routeName: "send_transaction_message_route"))

proc get_event_route_placeholder*(req: GetEventRouteRequest): GetEventRouteResponse =
  discard req
  GetEventRouteResponse(placeholder: RoutePlaceholder(routeName: "get_event_route"))

proc get_backfill_route_placeholder*(req: GetBackfillRouteRequest): GetBackfillRouteResponse =
  discard req
  GetBackfillRouteResponse(placeholder: RoutePlaceholder(routeName: "get_backfill_route"))

proc get_missing_events_route_placeholder*(req: GetMissingEventsRouteRequest): GetMissingEventsRouteResponse =
  discard req
  GetMissingEventsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_missing_events_route"))

proc get_event_authorization_route_placeholder*(req: GetEventAuthorizationRouteRequest): GetEventAuthorizationRouteResponse =
  discard req
  GetEventAuthorizationRouteResponse(placeholder: RoutePlaceholder(routeName: "get_event_authorization_route"))

proc get_room_state_route_placeholder*(req: GetRoomStateRouteRequest): GetRoomStateRouteResponse =
  discard req
  GetRoomStateRouteResponse(placeholder: RoutePlaceholder(routeName: "get_room_state_route"))

proc get_room_state_ids_route_placeholder*(req: GetRoomStateIdsRouteRequest): GetRoomStateIdsRouteResponse =
  discard req
  GetRoomStateIdsRouteResponse(placeholder: RoutePlaceholder(routeName: "get_room_state_ids_route"))

proc create_leave_event_template_route_placeholder*(req: CreateLeaveEventTemplateRouteRequest): CreateLeaveEventTemplateRouteResponse =
  discard req
  CreateLeaveEventTemplateRouteResponse(placeholder: RoutePlaceholder(routeName: "create_leave_event_template_route"))

proc create_knock_event_template_route_placeholder*(req: CreateKnockEventTemplateRouteRequest): CreateKnockEventTemplateRouteResponse =
  discard req
  CreateKnockEventTemplateRouteResponse(placeholder: RoutePlaceholder(routeName: "create_knock_event_template_route"))

proc create_leave_event_v1_route_placeholder*(req: CreateLeaveEventV1RouteRequest): CreateLeaveEventV1RouteResponse =
  discard req
  CreateLeaveEventV1RouteResponse(placeholder: RoutePlaceholder(routeName: "create_leave_event_v1_route"))

proc create_leave_event_v2_route_placeholder*(req: CreateLeaveEventV2RouteRequest): CreateLeaveEventV2RouteResponse =
  discard req
  CreateLeaveEventV2RouteResponse(placeholder: RoutePlaceholder(routeName: "create_leave_event_v2_route"))

proc create_knock_event_v1_route_placeholder*(req: CreateKnockEventV1RouteRequest): CreateKnockEventV1RouteResponse =
  discard req
  CreateKnockEventV1RouteResponse(placeholder: RoutePlaceholder(routeName: "create_knock_event_v1_route"))

proc create_join_event_template_route_placeholder*(req: CreateJoinEventTemplateRouteRequest): CreateJoinEventTemplateRouteResponse =
  discard req
  CreateJoinEventTemplateRouteResponse(placeholder: RoutePlaceholder(routeName: "create_join_event_template_route"))

proc create_join_event_v1_route_placeholder*(req: CreateJoinEventV1RouteRequest): CreateJoinEventV1RouteResponse =
  discard req
  CreateJoinEventV1RouteResponse(placeholder: RoutePlaceholder(routeName: "create_join_event_v1_route"))

proc create_join_event_v2_route_placeholder*(req: CreateJoinEventV2RouteRequest): CreateJoinEventV2RouteResponse =
  discard req
  CreateJoinEventV2RouteResponse(placeholder: RoutePlaceholder(routeName: "create_join_event_v2_route"))

proc create_invite_route_placeholder*(req: CreateInviteRouteRequest): CreateInviteRouteResponse =
  discard req
  CreateInviteRouteResponse(placeholder: RoutePlaceholder(routeName: "create_invite_route"))

proc get_devices_route_placeholder*(req: ServerGetDevicesRouteRequest): ServerGetDevicesRouteResponse =
  discard req
  ServerGetDevicesRouteResponse(placeholder: RoutePlaceholder(routeName: "get_devices_route"))

proc get_room_information_route_placeholder*(req: GetRoomInformationRouteRequest): GetRoomInformationRouteResponse =
  discard req
  GetRoomInformationRouteResponse(placeholder: RoutePlaceholder(routeName: "get_room_information_route"))

proc get_profile_information_route_placeholder*(req: GetProfileInformationRouteRequest): GetProfileInformationRouteResponse =
  discard req
  GetProfileInformationRouteResponse(placeholder: RoutePlaceholder(routeName: "get_profile_information_route"))

proc get_keys_route_placeholder*(req: ServerGetKeysRouteRequest): ServerGetKeysRouteResponse =
  discard req
  ServerGetKeysRouteResponse(placeholder: RoutePlaceholder(routeName: "get_keys_route"))

proc claim_keys_route_placeholder*(req: ServerClaimKeysRouteRequest): ServerClaimKeysRouteResponse =
  discard req
  ServerClaimKeysRouteResponse(placeholder: RoutePlaceholder(routeName: "claim_keys_route"))

proc get_hierarchy_route_placeholder*(req: ServerGetHierarchyRouteRequest): ServerGetHierarchyRouteResponse =
  discard req
  ServerGetHierarchyRouteResponse(placeholder: RoutePlaceholder(routeName: "get_hierarchy_route"))

proc well_known_server_placeholder*(req: WellKnownServerRequest): WellKnownServerResponse =
  discard req
  WellKnownServerResponse(placeholder: RoutePlaceholder(routeName: "well_known_server"))

proc get_content_route_placeholder*(req: ServerGetContentRouteRequest): ServerGetContentRouteResponse =
  discard req
  ServerGetContentRouteResponse(placeholder: RoutePlaceholder(routeName: "get_content_route"))

proc get_content_thumbnail_route_placeholder*(req: ServerGetContentThumbnailRouteRequest): ServerGetContentThumbnailRouteResponse =
  discard req
  ServerGetContentThumbnailRouteResponse(placeholder: RoutePlaceholder(routeName: "get_content_thumbnail_route"))
