## Generated by tools/generate_stubs.py. Do not edit manually.

type
  CrateFunctionCount* = object
    crate*: string
    functionCount*: int
    fileCount*: int

let RustCrateFunctionCounts*: seq[CrateFunctionCount] = @[
  CrateFunctionCount(crate: "admin", functionCount: 58, fileCount: 45),
  CrateFunctionCount(crate: "api", functionCount: 123, fileCount: 115),
  CrateFunctionCount(crate: "core", functionCount: 1197, fileCount: 161),
  CrateFunctionCount(crate: "database", functionCount: 337, fileCount: 57),
  CrateFunctionCount(crate: "macros", functionCount: 24, fileCount: 9),
  CrateFunctionCount(crate: "main", functionCount: 48, fileCount: 14),
  CrateFunctionCount(crate: "router", functionCount: 19, fileCount: 9),
  CrateFunctionCount(crate: "service", functionCount: 1014, fileCount: 138),
]

const RustFunctionTotal* = 2820
