## Generated by tools/generate_stubs.py. Do not edit manually.

import std/tables
import config_values

type
  ConfigModel* = object
    server_name*: ConfigValue
    database_path*: ConfigValue
    new_user_displayname_suffix*: ConfigValue
    tls*: ConfigValue
    unix_socket_path*: ConfigValue
    unix_socket_perms*: ConfigValue
    database_backup_path*: ConfigValue
    database_backups_to_keep*: ConfigValue
    cache_capacity_modifier*: ConfigValue
    db_cache_capacity_mb*: ConfigValue
    db_write_buffer_capacity_mb*: ConfigValue
    pdu_cache_capacity*: ConfigValue
    auth_chain_cache_capacity*: ConfigValue
    shorteventid_cache_capacity*: ConfigValue
    eventidshort_cache_capacity*: ConfigValue
    eventid_pdu_cache_capacity*: ConfigValue
    shortstatekey_cache_capacity*: ConfigValue
    statekeyshort_cache_capacity*: ConfigValue
    servernameevent_data_cache_capacity*: ConfigValue
    stateinfo_cache_capacity*: ConfigValue
    roomid_spacehierarchy_cache_capacity*: ConfigValue
    client_sync_timeout_min*: ConfigValue
    client_sync_timeout_default*: ConfigValue
    client_sync_timeout_max*: ConfigValue
    dns_cache_entries*: ConfigValue
    dns_min_ttl*: ConfigValue
    dns_min_ttl_nxdomain*: ConfigValue
    dns_attempts*: ConfigValue
    dns_timeout*: ConfigValue
    dns_tcp_fallback*: ConfigValue
    query_all_nameservers*: ConfigValue
    query_over_tcp_only*: ConfigValue
    ip_lookup_strategy*: ConfigValue
    dns_passthru_domains*: ConfigValue
    dns_passthru_appservices*: ConfigValue
    dns_case_randomization*: ConfigValue
    max_request_size*: ConfigValue
    max_fetch_prev_events*: ConfigValue
    request_conn_timeout*: ConfigValue
    request_timeout*: ConfigValue
    request_total_timeout*: ConfigValue
    request_idle_timeout*: ConfigValue
    request_idle_per_host*: ConfigValue
    well_known_conn_timeout*: ConfigValue
    well_known_timeout*: ConfigValue
    federation_timeout*: ConfigValue
    federation_idle_timeout*: ConfigValue
    federation_idle_per_host*: ConfigValue
    sender_timeout*: ConfigValue
    sender_idle_timeout*: ConfigValue
    sender_retry_backoff_limit*: ConfigValue
    appservice_timeout*: ConfigValue
    appservice_idle_timeout*: ConfigValue
    pusher_idle_timeout*: ConfigValue
    client_receive_timeout*: ConfigValue
    client_request_timeout*: ConfigValue
    client_response_timeout*: ConfigValue
    client_shutdown_timeout*: ConfigValue
    sender_shutdown_timeout*: ConfigValue
    allow_registration*: ConfigValue
    yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse*: ConfigValue
    registration_token*: ConfigValue
    registration_token_file*: ConfigValue
    allow_encryption*: ConfigValue
    encryption_enabled_by_default_for_room_type*: ConfigValue
    allow_federation*: ConfigValue
    federate_created_rooms*: ConfigValue
    federation_loopback*: ConfigValue
    forget_forced_upon_leave*: ConfigValue
    require_auth_for_profile_requests*: ConfigValue
    allow_public_room_directory_over_federation*: ConfigValue
    allow_public_room_directory_without_auth*: ConfigValue
    allow_public_room_search_by_id*: ConfigValue
    allow_unlisted_room_search_by_id*: ConfigValue
    show_all_local_users_in_user_directory*: ConfigValue
    turn_allow_guests*: ConfigValue
    lockdown_public_room_directory*: ConfigValue
    allow_device_name_federation*: ConfigValue
    allow_inbound_profile_lookup_federation_requests*: ConfigValue
    allow_room_creation*: ConfigValue
    allow_unstable_room_versions*: ConfigValue
    allow_experimental_room_versions*: ConfigValue
    default_room_version*: ConfigValue
    well_known*: ConfigValue
    allow_jaeger*: ConfigValue
    jaeger_filter*: ConfigValue
    tracing_flame*: ConfigValue
    tracing_flame_filter*: ConfigValue
    tracing_flame_output_path*: ConfigValue
    proxy*: ConfigValue
    trusted_servers*: ConfigValue
    query_trusted_key_servers_first*: ConfigValue
    query_trusted_key_servers_first_on_join*: ConfigValue
    only_query_trusted_key_servers*: ConfigValue
    trusted_server_batch_size*: ConfigValue
    log*: ConfigValue
    log_colors*: ConfigValue
    log_compact*: ConfigValue
    log_span_events*: ConfigValue
    log_filter_regex*: ConfigValue
    log_thread_ids*: ConfigValue
    log_to_stderr*: ConfigValue
    log_enable*: ConfigValue
    log_global_default*: ConfigValue
    openid_token_ttl*: ConfigValue
    login_via_existing_session*: ConfigValue
    login_via_token*: ConfigValue
    login_token_ttl*: ConfigValue
    access_token_ttl*: ConfigValue
    turn_username*: ConfigValue
    turn_password*: ConfigValue
    turn_uris*: ConfigValue
    turn_secret*: ConfigValue
    turn_secret_file*: ConfigValue
    turn_ttl*: ConfigValue
    auto_join_rooms*: ConfigValue
    auto_deactivate_banned_room_attempts*: ConfigValue
    rocksdb_log_level*: ConfigValue
    rocksdb_log_stderr*: ConfigValue
    rocksdb_max_log_file_size*: ConfigValue
    rocksdb_log_time_to_roll*: ConfigValue
    rocksdb_optimize_for_spinning_disks*: ConfigValue
    rocksdb_direct_io*: ConfigValue
    rocksdb_parallelism_threads*: ConfigValue
    rocksdb_max_log_files*: ConfigValue
    rocksdb_compression_algo*: ConfigValue
    rocksdb_compression_level*: ConfigValue
    rocksdb_bottommost_compression_level*: ConfigValue
    rocksdb_bottommost_compression*: ConfigValue
    rocksdb_recovery_mode*: ConfigValue
    rocksdb_paranoid_file_checks*: ConfigValue
    rocksdb_checksums*: ConfigValue
    rocksdb_atomic_flush*: ConfigValue
    rocksdb_repair*: ConfigValue
    rocksdb_read_only*: ConfigValue
    rocksdb_secondary*: ConfigValue
    rocksdb_compaction_prio_idle*: ConfigValue
    rocksdb_compaction_ioprio_idle*: ConfigValue
    rocksdb_compaction*: ConfigValue
    rocksdb_stats_level*: ConfigValue
    rocksdb_never_drop_columns*: ConfigValue
    emergency_password*: ConfigValue
    notification_push_path*: ConfigValue
    push_everything*: ConfigValue
    calculate_heroes*: ConfigValue
    allow_local_presence*: ConfigValue
    allow_incoming_presence*: ConfigValue
    allow_outgoing_presence*: ConfigValue
    presence_idle_timeout_s*: ConfigValue
    presence_offline_timeout_s*: ConfigValue
    presence_timeout_remote_users*: ConfigValue
    suppress_push_when_active*: ConfigValue
    allow_incoming_read_receipts*: ConfigValue
    allow_outgoing_read_receipts*: ConfigValue
    allow_outgoing_typing*: ConfigValue
    allow_incoming_typing*: ConfigValue
    typing_federation_timeout_s*: ConfigValue
    typing_client_timeout_min_s*: ConfigValue
    typing_client_timeout_max_s*: ConfigValue
    zstd_compression*: ConfigValue
    gzip_compression*: ConfigValue
    brotli_compression*: ConfigValue
    allow_guest_registration*: ConfigValue
    log_guest_registrations*: ConfigValue
    allow_guests_auto_join_rooms*: ConfigValue
    allow_legacy_media*: ConfigValue
    request_legacy_media*: ConfigValue
    freeze_legacy_media*: ConfigValue
    media_startup_check*: ConfigValue
    media_compat_file_link*: ConfigValue
    prune_missing_media*: ConfigValue
    prevent_media_downloads_from*: ConfigValue
    forbidden_remote_server_names*: ConfigValue
    forbidden_remote_room_directory_server_names*: ConfigValue
    ip_range_denylist*: ConfigValue
    url_preview_bound_interface*: ConfigValue
    url_preview_domain_contains_allowlist*: ConfigValue
    url_preview_domain_explicit_allowlist*: ConfigValue
    url_preview_domain_explicit_denylist*: ConfigValue
    url_preview_url_contains_allowlist*: ConfigValue
    url_preview_max_spider_size*: ConfigValue
    url_preview_check_root_domain*: ConfigValue
    forbidden_alias_names*: ConfigValue
    forbidden_usernames*: ConfigValue
    deprioritize_joins_through_servers*: ConfigValue
    max_make_join_attempts_per_join_attempt*: ConfigValue
    max_join_attempts_per_join_request*: ConfigValue
    startup_netburst*: ConfigValue
    startup_netburst_keep*: ConfigValue
    block_non_admin_invites*: ConfigValue
    admin_escape_commands*: ConfigValue
    admin_console_automatic*: ConfigValue
    admin_execute*: ConfigValue
    admin_execute_errors_ignore*: ConfigValue
    admin_signal_execute*: ConfigValue
    admin_log_capture*: ConfigValue
    admin_room_tag*: ConfigValue
    grant_admin_to_first_user*: ConfigValue
    create_admin_room*: ConfigValue
    federate_admin_room*: ConfigValue
    sentry*: ConfigValue
    sentry_endpoint*: ConfigValue
    sentry_send_server_name*: ConfigValue
    sentry_traces_sample_rate*: ConfigValue
    sentry_attach_stacktrace*: ConfigValue
    sentry_send_panic*: ConfigValue
    sentry_send_error*: ConfigValue
    sentry_filter*: ConfigValue
    tokio_console*: ConfigValue
    test*: ConfigValue
    admin_room_notices*: ConfigValue
    save_unredacted_events*: ConfigValue
    redaction_retention_seconds*: ConfigValue
    allow_room_admins_to_request_unredacted_events*: ConfigValue
    db_pool_affinity*: ConfigValue
    db_pool_workers*: ConfigValue
    db_pool_workers_limit*: ConfigValue
    db_pool_max_workers*: ConfigValue
    db_pool_queue_mult*: ConfigValue
    stream_width_default*: ConfigValue
    stream_width_scale*: ConfigValue
    stream_amplification*: ConfigValue
    sender_workers*: ConfigValue
    listening*: ConfigValue
    config_reload_signal*: ConfigValue
    allow_invalid_tls_certificates*: ConfigValue
    access_control_allow_origin*: ConfigValue
    hydra_backports*: ConfigValue
    delete_rooms_after_leave*: ConfigValue
    one_time_key_limit*: ConfigValue
    single_sso*: ConfigValue
    sso_custom_providers_page*: ConfigValue
    sso_aware_preferred*: ConfigValue
    blurhashing*: ConfigValue
    ldap*: ConfigValue
    jwt*: ConfigValue
    appservice*: ConfigValue
    identity_provider*: ConfigValue
    certs*: ConfigValue
    key*: ConfigValue
    dual_protocol*: ConfigValue
    client*: ConfigValue
    server*: ConfigValue
    support_page*: ConfigValue
    support_role*: ConfigValue
    support_email*: ConfigValue
    support_mxid*: ConfigValue
    rtc_transports*: ConfigValue
    components_x*: ConfigValue
    components_y*: ConfigValue
    blurhash_max_raw_size*: ConfigValue
    enable*: ConfigValue
    uri*: ConfigValue
    base_dn*: ConfigValue
    bind_dn*: ConfigValue
    bind_password_file*: ConfigValue
    filter*: ConfigValue
    uid_attribute*: ConfigValue
    mail_attribute*: ConfigValue
    name_attribute*: ConfigValue
    admin_base_dn*: ConfigValue
    admin_filter*: ConfigValue
    enable_2*: ConfigValue
    key_2*: ConfigValue
    format*: ConfigValue
    register_user*: ConfigValue
    algorithm*: ConfigValue
    audience*: ConfigValue
    issuer*: ConfigValue
    require_exp*: ConfigValue
    require_nbf*: ConfigValue
    validate_exp*: ConfigValue
    validate_nbf*: ConfigValue
    validate_signature*: ConfigValue
    brand*: ConfigValue
    client_id*: ConfigValue
    client_secret*: ConfigValue
    client_secret_file*: ConfigValue
    issuer_url*: ConfigValue
    callback_url*: ConfigValue
    default*: ConfigValue
    name*: ConfigValue
    icon*: ConfigValue
    scope*: ConfigValue
    userid_claims*: ConfigValue
    base_path*: ConfigValue
    discovery_url*: ConfigValue
    authorization_url*: ConfigValue
    token_url*: ConfigValue
    revocation_url*: ConfigValue
    introspection_url*: ConfigValue
    userinfo_url*: ConfigValue
    discovery*: ConfigValue
    grant_session_duration*: ConfigValue
    id*: ConfigValue
    url*: ConfigValue
    as_token*: ConfigValue
    hs_token*: ConfigValue
    sender_localpart*: ConfigValue
    users*: ConfigValue
    aliases*: ConfigValue
    rooms*: ConfigValue
    rate_limited*: ConfigValue
    protocols*: ConfigValue
    receive_ephemeral*: ConfigValue
    device_management*: ConfigValue
    exclusive*: ConfigValue
    regex*: ConfigValue

proc defaultConfigModel*(): ConfigModel =
  ConfigModel(
    server_name: newNullValue(),
    database_path: newNullValue(),
    new_user_displayname_suffix: newNullValue(),
    tls: newNullValue(),
    unix_socket_path: newNullValue(),
    unix_socket_perms: newNullValue(),
    database_backup_path: newNullValue(),
    database_backups_to_keep: newNullValue(),
    cache_capacity_modifier: newNullValue(),
    db_cache_capacity_mb: newNullValue(),
    db_write_buffer_capacity_mb: newNullValue(),
    pdu_cache_capacity: newNullValue(),
    auth_chain_cache_capacity: newNullValue(),
    shorteventid_cache_capacity: newNullValue(),
    eventidshort_cache_capacity: newNullValue(),
    eventid_pdu_cache_capacity: newNullValue(),
    shortstatekey_cache_capacity: newNullValue(),
    statekeyshort_cache_capacity: newNullValue(),
    servernameevent_data_cache_capacity: newNullValue(),
    stateinfo_cache_capacity: newNullValue(),
    roomid_spacehierarchy_cache_capacity: newNullValue(),
    client_sync_timeout_min: newNullValue(),
    client_sync_timeout_default: newNullValue(),
    client_sync_timeout_max: newNullValue(),
    dns_cache_entries: newNullValue(),
    dns_min_ttl: newNullValue(),
    dns_min_ttl_nxdomain: newNullValue(),
    dns_attempts: newNullValue(),
    dns_timeout: newNullValue(),
    dns_tcp_fallback: newNullValue(),
    query_all_nameservers: newNullValue(),
    query_over_tcp_only: newNullValue(),
    ip_lookup_strategy: newNullValue(),
    dns_passthru_domains: newNullValue(),
    dns_passthru_appservices: newNullValue(),
    dns_case_randomization: newNullValue(),
    max_request_size: newNullValue(),
    max_fetch_prev_events: newNullValue(),
    request_conn_timeout: newNullValue(),
    request_timeout: newNullValue(),
    request_total_timeout: newNullValue(),
    request_idle_timeout: newNullValue(),
    request_idle_per_host: newNullValue(),
    well_known_conn_timeout: newNullValue(),
    well_known_timeout: newNullValue(),
    federation_timeout: newNullValue(),
    federation_idle_timeout: newNullValue(),
    federation_idle_per_host: newNullValue(),
    sender_timeout: newNullValue(),
    sender_idle_timeout: newNullValue(),
    sender_retry_backoff_limit: newNullValue(),
    appservice_timeout: newNullValue(),
    appservice_idle_timeout: newNullValue(),
    pusher_idle_timeout: newNullValue(),
    client_receive_timeout: newNullValue(),
    client_request_timeout: newNullValue(),
    client_response_timeout: newNullValue(),
    client_shutdown_timeout: newNullValue(),
    sender_shutdown_timeout: newNullValue(),
    allow_registration: newNullValue(),
    yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse: newNullValue(),
    registration_token: newNullValue(),
    registration_token_file: newNullValue(),
    allow_encryption: newNullValue(),
    encryption_enabled_by_default_for_room_type: newNullValue(),
    allow_federation: newNullValue(),
    federate_created_rooms: newNullValue(),
    federation_loopback: newNullValue(),
    forget_forced_upon_leave: newNullValue(),
    require_auth_for_profile_requests: newNullValue(),
    allow_public_room_directory_over_federation: newNullValue(),
    allow_public_room_directory_without_auth: newNullValue(),
    allow_public_room_search_by_id: newNullValue(),
    allow_unlisted_room_search_by_id: newNullValue(),
    show_all_local_users_in_user_directory: newNullValue(),
    turn_allow_guests: newNullValue(),
    lockdown_public_room_directory: newNullValue(),
    allow_device_name_federation: newNullValue(),
    allow_inbound_profile_lookup_federation_requests: newNullValue(),
    allow_room_creation: newNullValue(),
    allow_unstable_room_versions: newNullValue(),
    allow_experimental_room_versions: newNullValue(),
    default_room_version: newNullValue(),
    well_known: newNullValue(),
    allow_jaeger: newNullValue(),
    jaeger_filter: newNullValue(),
    tracing_flame: newNullValue(),
    tracing_flame_filter: newNullValue(),
    tracing_flame_output_path: newNullValue(),
    proxy: newNullValue(),
    trusted_servers: newNullValue(),
    query_trusted_key_servers_first: newNullValue(),
    query_trusted_key_servers_first_on_join: newNullValue(),
    only_query_trusted_key_servers: newNullValue(),
    trusted_server_batch_size: newNullValue(),
    log: newNullValue(),
    log_colors: newNullValue(),
    log_compact: newNullValue(),
    log_span_events: newNullValue(),
    log_filter_regex: newNullValue(),
    log_thread_ids: newNullValue(),
    log_to_stderr: newNullValue(),
    log_enable: newNullValue(),
    log_global_default: newNullValue(),
    openid_token_ttl: newNullValue(),
    login_via_existing_session: newNullValue(),
    login_via_token: newNullValue(),
    login_token_ttl: newNullValue(),
    access_token_ttl: newNullValue(),
    turn_username: newNullValue(),
    turn_password: newNullValue(),
    turn_uris: newNullValue(),
    turn_secret: newNullValue(),
    turn_secret_file: newNullValue(),
    turn_ttl: newNullValue(),
    auto_join_rooms: newNullValue(),
    auto_deactivate_banned_room_attempts: newNullValue(),
    rocksdb_log_level: newNullValue(),
    rocksdb_log_stderr: newNullValue(),
    rocksdb_max_log_file_size: newNullValue(),
    rocksdb_log_time_to_roll: newNullValue(),
    rocksdb_optimize_for_spinning_disks: newNullValue(),
    rocksdb_direct_io: newNullValue(),
    rocksdb_parallelism_threads: newNullValue(),
    rocksdb_max_log_files: newNullValue(),
    rocksdb_compression_algo: newNullValue(),
    rocksdb_compression_level: newNullValue(),
    rocksdb_bottommost_compression_level: newNullValue(),
    rocksdb_bottommost_compression: newNullValue(),
    rocksdb_recovery_mode: newNullValue(),
    rocksdb_paranoid_file_checks: newNullValue(),
    rocksdb_checksums: newNullValue(),
    rocksdb_atomic_flush: newNullValue(),
    rocksdb_repair: newNullValue(),
    rocksdb_read_only: newNullValue(),
    rocksdb_secondary: newNullValue(),
    rocksdb_compaction_prio_idle: newNullValue(),
    rocksdb_compaction_ioprio_idle: newNullValue(),
    rocksdb_compaction: newNullValue(),
    rocksdb_stats_level: newNullValue(),
    rocksdb_never_drop_columns: newNullValue(),
    emergency_password: newNullValue(),
    notification_push_path: newNullValue(),
    push_everything: newNullValue(),
    calculate_heroes: newNullValue(),
    allow_local_presence: newNullValue(),
    allow_incoming_presence: newNullValue(),
    allow_outgoing_presence: newNullValue(),
    presence_idle_timeout_s: newNullValue(),
    presence_offline_timeout_s: newNullValue(),
    presence_timeout_remote_users: newNullValue(),
    suppress_push_when_active: newNullValue(),
    allow_incoming_read_receipts: newNullValue(),
    allow_outgoing_read_receipts: newNullValue(),
    allow_outgoing_typing: newNullValue(),
    allow_incoming_typing: newNullValue(),
    typing_federation_timeout_s: newNullValue(),
    typing_client_timeout_min_s: newNullValue(),
    typing_client_timeout_max_s: newNullValue(),
    zstd_compression: newNullValue(),
    gzip_compression: newNullValue(),
    brotli_compression: newNullValue(),
    allow_guest_registration: newNullValue(),
    log_guest_registrations: newNullValue(),
    allow_guests_auto_join_rooms: newNullValue(),
    allow_legacy_media: newNullValue(),
    request_legacy_media: newNullValue(),
    freeze_legacy_media: newNullValue(),
    media_startup_check: newNullValue(),
    media_compat_file_link: newNullValue(),
    prune_missing_media: newNullValue(),
    prevent_media_downloads_from: newNullValue(),
    forbidden_remote_server_names: newNullValue(),
    forbidden_remote_room_directory_server_names: newNullValue(),
    ip_range_denylist: newNullValue(),
    url_preview_bound_interface: newNullValue(),
    url_preview_domain_contains_allowlist: newNullValue(),
    url_preview_domain_explicit_allowlist: newNullValue(),
    url_preview_domain_explicit_denylist: newNullValue(),
    url_preview_url_contains_allowlist: newNullValue(),
    url_preview_max_spider_size: newNullValue(),
    url_preview_check_root_domain: newNullValue(),
    forbidden_alias_names: newNullValue(),
    forbidden_usernames: newNullValue(),
    deprioritize_joins_through_servers: newNullValue(),
    max_make_join_attempts_per_join_attempt: newNullValue(),
    max_join_attempts_per_join_request: newNullValue(),
    startup_netburst: newNullValue(),
    startup_netburst_keep: newNullValue(),
    block_non_admin_invites: newNullValue(),
    admin_escape_commands: newNullValue(),
    admin_console_automatic: newNullValue(),
    admin_execute: newNullValue(),
    admin_execute_errors_ignore: newNullValue(),
    admin_signal_execute: newNullValue(),
    admin_log_capture: newNullValue(),
    admin_room_tag: newNullValue(),
    grant_admin_to_first_user: newNullValue(),
    create_admin_room: newNullValue(),
    federate_admin_room: newNullValue(),
    sentry: newNullValue(),
    sentry_endpoint: newNullValue(),
    sentry_send_server_name: newNullValue(),
    sentry_traces_sample_rate: newNullValue(),
    sentry_attach_stacktrace: newNullValue(),
    sentry_send_panic: newNullValue(),
    sentry_send_error: newNullValue(),
    sentry_filter: newNullValue(),
    tokio_console: newNullValue(),
    test: newNullValue(),
    admin_room_notices: newNullValue(),
    save_unredacted_events: newNullValue(),
    redaction_retention_seconds: newNullValue(),
    allow_room_admins_to_request_unredacted_events: newNullValue(),
    db_pool_affinity: newNullValue(),
    db_pool_workers: newNullValue(),
    db_pool_workers_limit: newNullValue(),
    db_pool_max_workers: newNullValue(),
    db_pool_queue_mult: newNullValue(),
    stream_width_default: newNullValue(),
    stream_width_scale: newNullValue(),
    stream_amplification: newNullValue(),
    sender_workers: newNullValue(),
    listening: newNullValue(),
    config_reload_signal: newNullValue(),
    allow_invalid_tls_certificates: newNullValue(),
    access_control_allow_origin: newNullValue(),
    hydra_backports: newNullValue(),
    delete_rooms_after_leave: newNullValue(),
    one_time_key_limit: newNullValue(),
    single_sso: newNullValue(),
    sso_custom_providers_page: newNullValue(),
    sso_aware_preferred: newNullValue(),
    blurhashing: newNullValue(),
    ldap: newNullValue(),
    jwt: newNullValue(),
    appservice: newNullValue(),
    identity_provider: newNullValue(),
    certs: newNullValue(),
    key: newNullValue(),
    dual_protocol: newNullValue(),
    client: newNullValue(),
    server: newNullValue(),
    support_page: newNullValue(),
    support_role: newNullValue(),
    support_email: newNullValue(),
    support_mxid: newNullValue(),
    rtc_transports: newNullValue(),
    components_x: newNullValue(),
    components_y: newNullValue(),
    blurhash_max_raw_size: newNullValue(),
    enable: newNullValue(),
    uri: newNullValue(),
    base_dn: newNullValue(),
    bind_dn: newNullValue(),
    bind_password_file: newNullValue(),
    filter: newNullValue(),
    uid_attribute: newNullValue(),
    mail_attribute: newNullValue(),
    name_attribute: newNullValue(),
    admin_base_dn: newNullValue(),
    admin_filter: newNullValue(),
    enable_2: newNullValue(),
    key_2: newNullValue(),
    format: newNullValue(),
    register_user: newNullValue(),
    algorithm: newNullValue(),
    audience: newNullValue(),
    issuer: newNullValue(),
    require_exp: newNullValue(),
    require_nbf: newNullValue(),
    validate_exp: newNullValue(),
    validate_nbf: newNullValue(),
    validate_signature: newNullValue(),
    brand: newNullValue(),
    client_id: newNullValue(),
    client_secret: newNullValue(),
    client_secret_file: newNullValue(),
    issuer_url: newNullValue(),
    callback_url: newNullValue(),
    default: newNullValue(),
    name: newNullValue(),
    icon: newNullValue(),
    scope: newNullValue(),
    userid_claims: newNullValue(),
    base_path: newNullValue(),
    discovery_url: newNullValue(),
    authorization_url: newNullValue(),
    token_url: newNullValue(),
    revocation_url: newNullValue(),
    introspection_url: newNullValue(),
    userinfo_url: newNullValue(),
    discovery: newNullValue(),
    grant_session_duration: newNullValue(),
    id: newNullValue(),
    url: newNullValue(),
    as_token: newNullValue(),
    hs_token: newNullValue(),
    sender_localpart: newNullValue(),
    users: newNullValue(),
    aliases: newNullValue(),
    rooms: newNullValue(),
    rate_limited: newNullValue(),
    protocols: newNullValue(),
    receive_ephemeral: newNullValue(),
    device_management: newNullValue(),
    exclusive: newNullValue(),
    regex: newNullValue(),
  )

proc toFlatConfig*(model: ConfigModel): FlatConfig =
  result = initFlatConfig()
  result["server_name"] = model.server_name
  result["database_path"] = model.database_path
  result["new_user_displayname_suffix"] = model.new_user_displayname_suffix
  result["tls"] = model.tls
  result["unix_socket_path"] = model.unix_socket_path
  result["unix_socket_perms"] = model.unix_socket_perms
  result["database_backup_path"] = model.database_backup_path
  result["database_backups_to_keep"] = model.database_backups_to_keep
  result["cache_capacity_modifier"] = model.cache_capacity_modifier
  result["db_cache_capacity_mb"] = model.db_cache_capacity_mb
  result["db_write_buffer_capacity_mb"] = model.db_write_buffer_capacity_mb
  result["pdu_cache_capacity"] = model.pdu_cache_capacity
  result["auth_chain_cache_capacity"] = model.auth_chain_cache_capacity
  result["shorteventid_cache_capacity"] = model.shorteventid_cache_capacity
  result["eventidshort_cache_capacity"] = model.eventidshort_cache_capacity
  result["eventid_pdu_cache_capacity"] = model.eventid_pdu_cache_capacity
  result["shortstatekey_cache_capacity"] = model.shortstatekey_cache_capacity
  result["statekeyshort_cache_capacity"] = model.statekeyshort_cache_capacity
  result["servernameevent_data_cache_capacity"] = model.servernameevent_data_cache_capacity
  result["stateinfo_cache_capacity"] = model.stateinfo_cache_capacity
  result["roomid_spacehierarchy_cache_capacity"] = model.roomid_spacehierarchy_cache_capacity
  result["client_sync_timeout_min"] = model.client_sync_timeout_min
  result["client_sync_timeout_default"] = model.client_sync_timeout_default
  result["client_sync_timeout_max"] = model.client_sync_timeout_max
  result["dns_cache_entries"] = model.dns_cache_entries
  result["dns_min_ttl"] = model.dns_min_ttl
  result["dns_min_ttl_nxdomain"] = model.dns_min_ttl_nxdomain
  result["dns_attempts"] = model.dns_attempts
  result["dns_timeout"] = model.dns_timeout
  result["dns_tcp_fallback"] = model.dns_tcp_fallback
  result["query_all_nameservers"] = model.query_all_nameservers
  result["query_over_tcp_only"] = model.query_over_tcp_only
  result["ip_lookup_strategy"] = model.ip_lookup_strategy
  result["dns_passthru_domains"] = model.dns_passthru_domains
  result["dns_passthru_appservices"] = model.dns_passthru_appservices
  result["dns_case_randomization"] = model.dns_case_randomization
  result["max_request_size"] = model.max_request_size
  result["max_fetch_prev_events"] = model.max_fetch_prev_events
  result["request_conn_timeout"] = model.request_conn_timeout
  result["request_timeout"] = model.request_timeout
  result["request_total_timeout"] = model.request_total_timeout
  result["request_idle_timeout"] = model.request_idle_timeout
  result["request_idle_per_host"] = model.request_idle_per_host
  result["well_known_conn_timeout"] = model.well_known_conn_timeout
  result["well_known_timeout"] = model.well_known_timeout
  result["federation_timeout"] = model.federation_timeout
  result["federation_idle_timeout"] = model.federation_idle_timeout
  result["federation_idle_per_host"] = model.federation_idle_per_host
  result["sender_timeout"] = model.sender_timeout
  result["sender_idle_timeout"] = model.sender_idle_timeout
  result["sender_retry_backoff_limit"] = model.sender_retry_backoff_limit
  result["appservice_timeout"] = model.appservice_timeout
  result["appservice_idle_timeout"] = model.appservice_idle_timeout
  result["pusher_idle_timeout"] = model.pusher_idle_timeout
  result["client_receive_timeout"] = model.client_receive_timeout
  result["client_request_timeout"] = model.client_request_timeout
  result["client_response_timeout"] = model.client_response_timeout
  result["client_shutdown_timeout"] = model.client_shutdown_timeout
  result["sender_shutdown_timeout"] = model.sender_shutdown_timeout
  result["allow_registration"] = model.allow_registration
  result["yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse"] = model.yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse
  result["registration_token"] = model.registration_token
  result["registration_token_file"] = model.registration_token_file
  result["allow_encryption"] = model.allow_encryption
  result["encryption_enabled_by_default_for_room_type"] = model.encryption_enabled_by_default_for_room_type
  result["allow_federation"] = model.allow_federation
  result["federate_created_rooms"] = model.federate_created_rooms
  result["federation_loopback"] = model.federation_loopback
  result["forget_forced_upon_leave"] = model.forget_forced_upon_leave
  result["require_auth_for_profile_requests"] = model.require_auth_for_profile_requests
  result["allow_public_room_directory_over_federation"] = model.allow_public_room_directory_over_federation
  result["allow_public_room_directory_without_auth"] = model.allow_public_room_directory_without_auth
  result["allow_public_room_search_by_id"] = model.allow_public_room_search_by_id
  result["allow_unlisted_room_search_by_id"] = model.allow_unlisted_room_search_by_id
  result["show_all_local_users_in_user_directory"] = model.show_all_local_users_in_user_directory
  result["turn_allow_guests"] = model.turn_allow_guests
  result["lockdown_public_room_directory"] = model.lockdown_public_room_directory
  result["allow_device_name_federation"] = model.allow_device_name_federation
  result["allow_inbound_profile_lookup_federation_requests"] = model.allow_inbound_profile_lookup_federation_requests
  result["allow_room_creation"] = model.allow_room_creation
  result["allow_unstable_room_versions"] = model.allow_unstable_room_versions
  result["allow_experimental_room_versions"] = model.allow_experimental_room_versions
  result["default_room_version"] = model.default_room_version
  result["well_known"] = model.well_known
  result["allow_jaeger"] = model.allow_jaeger
  result["jaeger_filter"] = model.jaeger_filter
  result["tracing_flame"] = model.tracing_flame
  result["tracing_flame_filter"] = model.tracing_flame_filter
  result["tracing_flame_output_path"] = model.tracing_flame_output_path
  result["proxy"] = model.proxy
  result["trusted_servers"] = model.trusted_servers
  result["query_trusted_key_servers_first"] = model.query_trusted_key_servers_first
  result["query_trusted_key_servers_first_on_join"] = model.query_trusted_key_servers_first_on_join
  result["only_query_trusted_key_servers"] = model.only_query_trusted_key_servers
  result["trusted_server_batch_size"] = model.trusted_server_batch_size
  result["log"] = model.log
  result["log_colors"] = model.log_colors
  result["log_compact"] = model.log_compact
  result["log_span_events"] = model.log_span_events
  result["log_filter_regex"] = model.log_filter_regex
  result["log_thread_ids"] = model.log_thread_ids
  result["log_to_stderr"] = model.log_to_stderr
  result["log_enable"] = model.log_enable
  result["log_global_default"] = model.log_global_default
  result["openid_token_ttl"] = model.openid_token_ttl
  result["login_via_existing_session"] = model.login_via_existing_session
  result["login_via_token"] = model.login_via_token
  result["login_token_ttl"] = model.login_token_ttl
  result["access_token_ttl"] = model.access_token_ttl
  result["turn_username"] = model.turn_username
  result["turn_password"] = model.turn_password
  result["turn_uris"] = model.turn_uris
  result["turn_secret"] = model.turn_secret
  result["turn_secret_file"] = model.turn_secret_file
  result["turn_ttl"] = model.turn_ttl
  result["auto_join_rooms"] = model.auto_join_rooms
  result["auto_deactivate_banned_room_attempts"] = model.auto_deactivate_banned_room_attempts
  result["rocksdb_log_level"] = model.rocksdb_log_level
  result["rocksdb_log_stderr"] = model.rocksdb_log_stderr
  result["rocksdb_max_log_file_size"] = model.rocksdb_max_log_file_size
  result["rocksdb_log_time_to_roll"] = model.rocksdb_log_time_to_roll
  result["rocksdb_optimize_for_spinning_disks"] = model.rocksdb_optimize_for_spinning_disks
  result["rocksdb_direct_io"] = model.rocksdb_direct_io
  result["rocksdb_parallelism_threads"] = model.rocksdb_parallelism_threads
  result["rocksdb_max_log_files"] = model.rocksdb_max_log_files
  result["rocksdb_compression_algo"] = model.rocksdb_compression_algo
  result["rocksdb_compression_level"] = model.rocksdb_compression_level
  result["rocksdb_bottommost_compression_level"] = model.rocksdb_bottommost_compression_level
  result["rocksdb_bottommost_compression"] = model.rocksdb_bottommost_compression
  result["rocksdb_recovery_mode"] = model.rocksdb_recovery_mode
  result["rocksdb_paranoid_file_checks"] = model.rocksdb_paranoid_file_checks
  result["rocksdb_checksums"] = model.rocksdb_checksums
  result["rocksdb_atomic_flush"] = model.rocksdb_atomic_flush
  result["rocksdb_repair"] = model.rocksdb_repair
  result["rocksdb_read_only"] = model.rocksdb_read_only
  result["rocksdb_secondary"] = model.rocksdb_secondary
  result["rocksdb_compaction_prio_idle"] = model.rocksdb_compaction_prio_idle
  result["rocksdb_compaction_ioprio_idle"] = model.rocksdb_compaction_ioprio_idle
  result["rocksdb_compaction"] = model.rocksdb_compaction
  result["rocksdb_stats_level"] = model.rocksdb_stats_level
  result["rocksdb_never_drop_columns"] = model.rocksdb_never_drop_columns
  result["emergency_password"] = model.emergency_password
  result["notification_push_path"] = model.notification_push_path
  result["push_everything"] = model.push_everything
  result["calculate_heroes"] = model.calculate_heroes
  result["allow_local_presence"] = model.allow_local_presence
  result["allow_incoming_presence"] = model.allow_incoming_presence
  result["allow_outgoing_presence"] = model.allow_outgoing_presence
  result["presence_idle_timeout_s"] = model.presence_idle_timeout_s
  result["presence_offline_timeout_s"] = model.presence_offline_timeout_s
  result["presence_timeout_remote_users"] = model.presence_timeout_remote_users
  result["suppress_push_when_active"] = model.suppress_push_when_active
  result["allow_incoming_read_receipts"] = model.allow_incoming_read_receipts
  result["allow_outgoing_read_receipts"] = model.allow_outgoing_read_receipts
  result["allow_outgoing_typing"] = model.allow_outgoing_typing
  result["allow_incoming_typing"] = model.allow_incoming_typing
  result["typing_federation_timeout_s"] = model.typing_federation_timeout_s
  result["typing_client_timeout_min_s"] = model.typing_client_timeout_min_s
  result["typing_client_timeout_max_s"] = model.typing_client_timeout_max_s
  result["zstd_compression"] = model.zstd_compression
  result["gzip_compression"] = model.gzip_compression
  result["brotli_compression"] = model.brotli_compression
  result["allow_guest_registration"] = model.allow_guest_registration
  result["log_guest_registrations"] = model.log_guest_registrations
  result["allow_guests_auto_join_rooms"] = model.allow_guests_auto_join_rooms
  result["allow_legacy_media"] = model.allow_legacy_media
  result["request_legacy_media"] = model.request_legacy_media
  result["freeze_legacy_media"] = model.freeze_legacy_media
  result["media_startup_check"] = model.media_startup_check
  result["media_compat_file_link"] = model.media_compat_file_link
  result["prune_missing_media"] = model.prune_missing_media
  result["prevent_media_downloads_from"] = model.prevent_media_downloads_from
  result["forbidden_remote_server_names"] = model.forbidden_remote_server_names
  result["forbidden_remote_room_directory_server_names"] = model.forbidden_remote_room_directory_server_names
  result["ip_range_denylist"] = model.ip_range_denylist
  result["url_preview_bound_interface"] = model.url_preview_bound_interface
  result["url_preview_domain_contains_allowlist"] = model.url_preview_domain_contains_allowlist
  result["url_preview_domain_explicit_allowlist"] = model.url_preview_domain_explicit_allowlist
  result["url_preview_domain_explicit_denylist"] = model.url_preview_domain_explicit_denylist
  result["url_preview_url_contains_allowlist"] = model.url_preview_url_contains_allowlist
  result["url_preview_max_spider_size"] = model.url_preview_max_spider_size
  result["url_preview_check_root_domain"] = model.url_preview_check_root_domain
  result["forbidden_alias_names"] = model.forbidden_alias_names
  result["forbidden_usernames"] = model.forbidden_usernames
  result["deprioritize_joins_through_servers"] = model.deprioritize_joins_through_servers
  result["max_make_join_attempts_per_join_attempt"] = model.max_make_join_attempts_per_join_attempt
  result["max_join_attempts_per_join_request"] = model.max_join_attempts_per_join_request
  result["startup_netburst"] = model.startup_netburst
  result["startup_netburst_keep"] = model.startup_netburst_keep
  result["block_non_admin_invites"] = model.block_non_admin_invites
  result["admin_escape_commands"] = model.admin_escape_commands
  result["admin_console_automatic"] = model.admin_console_automatic
  result["admin_execute"] = model.admin_execute
  result["admin_execute_errors_ignore"] = model.admin_execute_errors_ignore
  result["admin_signal_execute"] = model.admin_signal_execute
  result["admin_log_capture"] = model.admin_log_capture
  result["admin_room_tag"] = model.admin_room_tag
  result["grant_admin_to_first_user"] = model.grant_admin_to_first_user
  result["create_admin_room"] = model.create_admin_room
  result["federate_admin_room"] = model.federate_admin_room
  result["sentry"] = model.sentry
  result["sentry_endpoint"] = model.sentry_endpoint
  result["sentry_send_server_name"] = model.sentry_send_server_name
  result["sentry_traces_sample_rate"] = model.sentry_traces_sample_rate
  result["sentry_attach_stacktrace"] = model.sentry_attach_stacktrace
  result["sentry_send_panic"] = model.sentry_send_panic
  result["sentry_send_error"] = model.sentry_send_error
  result["sentry_filter"] = model.sentry_filter
  result["tokio_console"] = model.tokio_console
  result["test"] = model.test
  result["admin_room_notices"] = model.admin_room_notices
  result["save_unredacted_events"] = model.save_unredacted_events
  result["redaction_retention_seconds"] = model.redaction_retention_seconds
  result["allow_room_admins_to_request_unredacted_events"] = model.allow_room_admins_to_request_unredacted_events
  result["db_pool_affinity"] = model.db_pool_affinity
  result["db_pool_workers"] = model.db_pool_workers
  result["db_pool_workers_limit"] = model.db_pool_workers_limit
  result["db_pool_max_workers"] = model.db_pool_max_workers
  result["db_pool_queue_mult"] = model.db_pool_queue_mult
  result["stream_width_default"] = model.stream_width_default
  result["stream_width_scale"] = model.stream_width_scale
  result["stream_amplification"] = model.stream_amplification
  result["sender_workers"] = model.sender_workers
  result["listening"] = model.listening
  result["config_reload_signal"] = model.config_reload_signal
  result["allow_invalid_tls_certificates"] = model.allow_invalid_tls_certificates
  result["access_control_allow_origin"] = model.access_control_allow_origin
  result["hydra_backports"] = model.hydra_backports
  result["delete_rooms_after_leave"] = model.delete_rooms_after_leave
  result["one_time_key_limit"] = model.one_time_key_limit
  result["single_sso"] = model.single_sso
  result["sso_custom_providers_page"] = model.sso_custom_providers_page
  result["sso_aware_preferred"] = model.sso_aware_preferred
  result["blurhashing"] = model.blurhashing
  result["ldap"] = model.ldap
  result["jwt"] = model.jwt
  result["appservice"] = model.appservice
  result["identity_provider"] = model.identity_provider
  result["certs"] = model.certs
  result["key"] = model.key
  result["dual_protocol"] = model.dual_protocol
  result["client"] = model.client
  result["server"] = model.server
  result["support_page"] = model.support_page
  result["support_role"] = model.support_role
  result["support_email"] = model.support_email
  result["support_mxid"] = model.support_mxid
  result["rtc_transports"] = model.rtc_transports
  result["components_x"] = model.components_x
  result["components_y"] = model.components_y
  result["blurhash_max_raw_size"] = model.blurhash_max_raw_size
  result["enable"] = model.enable
  result["uri"] = model.uri
  result["base_dn"] = model.base_dn
  result["bind_dn"] = model.bind_dn
  result["bind_password_file"] = model.bind_password_file
  result["filter"] = model.filter
  result["uid_attribute"] = model.uid_attribute
  result["mail_attribute"] = model.mail_attribute
  result["name_attribute"] = model.name_attribute
  result["admin_base_dn"] = model.admin_base_dn
  result["admin_filter"] = model.admin_filter
  result["enable"] = model.enable_2
  result["key"] = model.key_2
  result["format"] = model.format
  result["register_user"] = model.register_user
  result["algorithm"] = model.algorithm
  result["audience"] = model.audience
  result["issuer"] = model.issuer
  result["require_exp"] = model.require_exp
  result["require_nbf"] = model.require_nbf
  result["validate_exp"] = model.validate_exp
  result["validate_nbf"] = model.validate_nbf
  result["validate_signature"] = model.validate_signature
  result["brand"] = model.brand
  result["client_id"] = model.client_id
  result["client_secret"] = model.client_secret
  result["client_secret_file"] = model.client_secret_file
  result["issuer_url"] = model.issuer_url
  result["callback_url"] = model.callback_url
  result["default"] = model.default
  result["name"] = model.name
  result["icon"] = model.icon
  result["scope"] = model.scope
  result["userid_claims"] = model.userid_claims
  result["base_path"] = model.base_path
  result["discovery_url"] = model.discovery_url
  result["authorization_url"] = model.authorization_url
  result["token_url"] = model.token_url
  result["revocation_url"] = model.revocation_url
  result["introspection_url"] = model.introspection_url
  result["userinfo_url"] = model.userinfo_url
  result["discovery"] = model.discovery
  result["grant_session_duration"] = model.grant_session_duration
  result["id"] = model.id
  result["url"] = model.url
  result["as_token"] = model.as_token
  result["hs_token"] = model.hs_token
  result["sender_localpart"] = model.sender_localpart
  result["users"] = model.users
  result["aliases"] = model.aliases
  result["rooms"] = model.rooms
  result["rate_limited"] = model.rate_limited
  result["protocols"] = model.protocols
  result["receive_ephemeral"] = model.receive_ephemeral
  result["device_management"] = model.device_management
  result["exclusive"] = model.exclusive
  result["regex"] = model.regex

proc fromFlatConfig*(values: FlatConfig): ConfigModel =
  result = defaultConfigModel()
  if "server_name" in values:
    result.server_name = values["server_name"]
  if "database_path" in values:
    result.database_path = values["database_path"]
  if "new_user_displayname_suffix" in values:
    result.new_user_displayname_suffix = values["new_user_displayname_suffix"]
  if "tls" in values:
    result.tls = values["tls"]
  if "unix_socket_path" in values:
    result.unix_socket_path = values["unix_socket_path"]
  if "unix_socket_perms" in values:
    result.unix_socket_perms = values["unix_socket_perms"]
  if "database_backup_path" in values:
    result.database_backup_path = values["database_backup_path"]
  if "database_backups_to_keep" in values:
    result.database_backups_to_keep = values["database_backups_to_keep"]
  if "cache_capacity_modifier" in values:
    result.cache_capacity_modifier = values["cache_capacity_modifier"]
  if "db_cache_capacity_mb" in values:
    result.db_cache_capacity_mb = values["db_cache_capacity_mb"]
  if "db_write_buffer_capacity_mb" in values:
    result.db_write_buffer_capacity_mb = values["db_write_buffer_capacity_mb"]
  if "pdu_cache_capacity" in values:
    result.pdu_cache_capacity = values["pdu_cache_capacity"]
  if "auth_chain_cache_capacity" in values:
    result.auth_chain_cache_capacity = values["auth_chain_cache_capacity"]
  if "shorteventid_cache_capacity" in values:
    result.shorteventid_cache_capacity = values["shorteventid_cache_capacity"]
  if "eventidshort_cache_capacity" in values:
    result.eventidshort_cache_capacity = values["eventidshort_cache_capacity"]
  if "eventid_pdu_cache_capacity" in values:
    result.eventid_pdu_cache_capacity = values["eventid_pdu_cache_capacity"]
  if "shortstatekey_cache_capacity" in values:
    result.shortstatekey_cache_capacity = values["shortstatekey_cache_capacity"]
  if "statekeyshort_cache_capacity" in values:
    result.statekeyshort_cache_capacity = values["statekeyshort_cache_capacity"]
  if "servernameevent_data_cache_capacity" in values:
    result.servernameevent_data_cache_capacity = values["servernameevent_data_cache_capacity"]
  if "stateinfo_cache_capacity" in values:
    result.stateinfo_cache_capacity = values["stateinfo_cache_capacity"]
  if "roomid_spacehierarchy_cache_capacity" in values:
    result.roomid_spacehierarchy_cache_capacity = values["roomid_spacehierarchy_cache_capacity"]
  if "client_sync_timeout_min" in values:
    result.client_sync_timeout_min = values["client_sync_timeout_min"]
  if "client_sync_timeout_default" in values:
    result.client_sync_timeout_default = values["client_sync_timeout_default"]
  if "client_sync_timeout_max" in values:
    result.client_sync_timeout_max = values["client_sync_timeout_max"]
  if "dns_cache_entries" in values:
    result.dns_cache_entries = values["dns_cache_entries"]
  if "dns_min_ttl" in values:
    result.dns_min_ttl = values["dns_min_ttl"]
  if "dns_min_ttl_nxdomain" in values:
    result.dns_min_ttl_nxdomain = values["dns_min_ttl_nxdomain"]
  if "dns_attempts" in values:
    result.dns_attempts = values["dns_attempts"]
  if "dns_timeout" in values:
    result.dns_timeout = values["dns_timeout"]
  if "dns_tcp_fallback" in values:
    result.dns_tcp_fallback = values["dns_tcp_fallback"]
  if "query_all_nameservers" in values:
    result.query_all_nameservers = values["query_all_nameservers"]
  if "query_over_tcp_only" in values:
    result.query_over_tcp_only = values["query_over_tcp_only"]
  if "ip_lookup_strategy" in values:
    result.ip_lookup_strategy = values["ip_lookup_strategy"]
  if "dns_passthru_domains" in values:
    result.dns_passthru_domains = values["dns_passthru_domains"]
  if "dns_passthru_appservices" in values:
    result.dns_passthru_appservices = values["dns_passthru_appservices"]
  if "dns_case_randomization" in values:
    result.dns_case_randomization = values["dns_case_randomization"]
  if "max_request_size" in values:
    result.max_request_size = values["max_request_size"]
  if "max_fetch_prev_events" in values:
    result.max_fetch_prev_events = values["max_fetch_prev_events"]
  if "request_conn_timeout" in values:
    result.request_conn_timeout = values["request_conn_timeout"]
  if "request_timeout" in values:
    result.request_timeout = values["request_timeout"]
  if "request_total_timeout" in values:
    result.request_total_timeout = values["request_total_timeout"]
  if "request_idle_timeout" in values:
    result.request_idle_timeout = values["request_idle_timeout"]
  if "request_idle_per_host" in values:
    result.request_idle_per_host = values["request_idle_per_host"]
  if "well_known_conn_timeout" in values:
    result.well_known_conn_timeout = values["well_known_conn_timeout"]
  if "well_known_timeout" in values:
    result.well_known_timeout = values["well_known_timeout"]
  if "federation_timeout" in values:
    result.federation_timeout = values["federation_timeout"]
  if "federation_idle_timeout" in values:
    result.federation_idle_timeout = values["federation_idle_timeout"]
  if "federation_idle_per_host" in values:
    result.federation_idle_per_host = values["federation_idle_per_host"]
  if "sender_timeout" in values:
    result.sender_timeout = values["sender_timeout"]
  if "sender_idle_timeout" in values:
    result.sender_idle_timeout = values["sender_idle_timeout"]
  if "sender_retry_backoff_limit" in values:
    result.sender_retry_backoff_limit = values["sender_retry_backoff_limit"]
  if "appservice_timeout" in values:
    result.appservice_timeout = values["appservice_timeout"]
  if "appservice_idle_timeout" in values:
    result.appservice_idle_timeout = values["appservice_idle_timeout"]
  if "pusher_idle_timeout" in values:
    result.pusher_idle_timeout = values["pusher_idle_timeout"]
  if "client_receive_timeout" in values:
    result.client_receive_timeout = values["client_receive_timeout"]
  if "client_request_timeout" in values:
    result.client_request_timeout = values["client_request_timeout"]
  if "client_response_timeout" in values:
    result.client_response_timeout = values["client_response_timeout"]
  if "client_shutdown_timeout" in values:
    result.client_shutdown_timeout = values["client_shutdown_timeout"]
  if "sender_shutdown_timeout" in values:
    result.sender_shutdown_timeout = values["sender_shutdown_timeout"]
  if "allow_registration" in values:
    result.allow_registration = values["allow_registration"]
  if "yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse" in values:
    result.yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse = values["yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse"]
  if "registration_token" in values:
    result.registration_token = values["registration_token"]
  if "registration_token_file" in values:
    result.registration_token_file = values["registration_token_file"]
  if "allow_encryption" in values:
    result.allow_encryption = values["allow_encryption"]
  if "encryption_enabled_by_default_for_room_type" in values:
    result.encryption_enabled_by_default_for_room_type = values["encryption_enabled_by_default_for_room_type"]
  if "allow_federation" in values:
    result.allow_federation = values["allow_federation"]
  if "federate_created_rooms" in values:
    result.federate_created_rooms = values["federate_created_rooms"]
  if "federation_loopback" in values:
    result.federation_loopback = values["federation_loopback"]
  if "forget_forced_upon_leave" in values:
    result.forget_forced_upon_leave = values["forget_forced_upon_leave"]
  if "require_auth_for_profile_requests" in values:
    result.require_auth_for_profile_requests = values["require_auth_for_profile_requests"]
  if "allow_public_room_directory_over_federation" in values:
    result.allow_public_room_directory_over_federation = values["allow_public_room_directory_over_federation"]
  if "allow_public_room_directory_without_auth" in values:
    result.allow_public_room_directory_without_auth = values["allow_public_room_directory_without_auth"]
  if "allow_public_room_search_by_id" in values:
    result.allow_public_room_search_by_id = values["allow_public_room_search_by_id"]
  if "allow_unlisted_room_search_by_id" in values:
    result.allow_unlisted_room_search_by_id = values["allow_unlisted_room_search_by_id"]
  if "show_all_local_users_in_user_directory" in values:
    result.show_all_local_users_in_user_directory = values["show_all_local_users_in_user_directory"]
  if "turn_allow_guests" in values:
    result.turn_allow_guests = values["turn_allow_guests"]
  if "lockdown_public_room_directory" in values:
    result.lockdown_public_room_directory = values["lockdown_public_room_directory"]
  if "allow_device_name_federation" in values:
    result.allow_device_name_federation = values["allow_device_name_federation"]
  if "allow_inbound_profile_lookup_federation_requests" in values:
    result.allow_inbound_profile_lookup_federation_requests = values["allow_inbound_profile_lookup_federation_requests"]
  if "allow_room_creation" in values:
    result.allow_room_creation = values["allow_room_creation"]
  if "allow_unstable_room_versions" in values:
    result.allow_unstable_room_versions = values["allow_unstable_room_versions"]
  if "allow_experimental_room_versions" in values:
    result.allow_experimental_room_versions = values["allow_experimental_room_versions"]
  if "default_room_version" in values:
    result.default_room_version = values["default_room_version"]
  if "well_known" in values:
    result.well_known = values["well_known"]
  if "allow_jaeger" in values:
    result.allow_jaeger = values["allow_jaeger"]
  if "jaeger_filter" in values:
    result.jaeger_filter = values["jaeger_filter"]
  if "tracing_flame" in values:
    result.tracing_flame = values["tracing_flame"]
  if "tracing_flame_filter" in values:
    result.tracing_flame_filter = values["tracing_flame_filter"]
  if "tracing_flame_output_path" in values:
    result.tracing_flame_output_path = values["tracing_flame_output_path"]
  if "proxy" in values:
    result.proxy = values["proxy"]
  if "trusted_servers" in values:
    result.trusted_servers = values["trusted_servers"]
  if "query_trusted_key_servers_first" in values:
    result.query_trusted_key_servers_first = values["query_trusted_key_servers_first"]
  if "query_trusted_key_servers_first_on_join" in values:
    result.query_trusted_key_servers_first_on_join = values["query_trusted_key_servers_first_on_join"]
  if "only_query_trusted_key_servers" in values:
    result.only_query_trusted_key_servers = values["only_query_trusted_key_servers"]
  if "trusted_server_batch_size" in values:
    result.trusted_server_batch_size = values["trusted_server_batch_size"]
  if "log" in values:
    result.log = values["log"]
  if "log_colors" in values:
    result.log_colors = values["log_colors"]
  if "log_compact" in values:
    result.log_compact = values["log_compact"]
  if "log_span_events" in values:
    result.log_span_events = values["log_span_events"]
  if "log_filter_regex" in values:
    result.log_filter_regex = values["log_filter_regex"]
  if "log_thread_ids" in values:
    result.log_thread_ids = values["log_thread_ids"]
  if "log_to_stderr" in values:
    result.log_to_stderr = values["log_to_stderr"]
  if "log_enable" in values:
    result.log_enable = values["log_enable"]
  if "log_global_default" in values:
    result.log_global_default = values["log_global_default"]
  if "openid_token_ttl" in values:
    result.openid_token_ttl = values["openid_token_ttl"]
  if "login_via_existing_session" in values:
    result.login_via_existing_session = values["login_via_existing_session"]
  if "login_via_token" in values:
    result.login_via_token = values["login_via_token"]
  if "login_token_ttl" in values:
    result.login_token_ttl = values["login_token_ttl"]
  if "access_token_ttl" in values:
    result.access_token_ttl = values["access_token_ttl"]
  if "turn_username" in values:
    result.turn_username = values["turn_username"]
  if "turn_password" in values:
    result.turn_password = values["turn_password"]
  if "turn_uris" in values:
    result.turn_uris = values["turn_uris"]
  if "turn_secret" in values:
    result.turn_secret = values["turn_secret"]
  if "turn_secret_file" in values:
    result.turn_secret_file = values["turn_secret_file"]
  if "turn_ttl" in values:
    result.turn_ttl = values["turn_ttl"]
  if "auto_join_rooms" in values:
    result.auto_join_rooms = values["auto_join_rooms"]
  if "auto_deactivate_banned_room_attempts" in values:
    result.auto_deactivate_banned_room_attempts = values["auto_deactivate_banned_room_attempts"]
  if "rocksdb_log_level" in values:
    result.rocksdb_log_level = values["rocksdb_log_level"]
  if "rocksdb_log_stderr" in values:
    result.rocksdb_log_stderr = values["rocksdb_log_stderr"]
  if "rocksdb_max_log_file_size" in values:
    result.rocksdb_max_log_file_size = values["rocksdb_max_log_file_size"]
  if "rocksdb_log_time_to_roll" in values:
    result.rocksdb_log_time_to_roll = values["rocksdb_log_time_to_roll"]
  if "rocksdb_optimize_for_spinning_disks" in values:
    result.rocksdb_optimize_for_spinning_disks = values["rocksdb_optimize_for_spinning_disks"]
  if "rocksdb_direct_io" in values:
    result.rocksdb_direct_io = values["rocksdb_direct_io"]
  if "rocksdb_parallelism_threads" in values:
    result.rocksdb_parallelism_threads = values["rocksdb_parallelism_threads"]
  if "rocksdb_max_log_files" in values:
    result.rocksdb_max_log_files = values["rocksdb_max_log_files"]
  if "rocksdb_compression_algo" in values:
    result.rocksdb_compression_algo = values["rocksdb_compression_algo"]
  if "rocksdb_compression_level" in values:
    result.rocksdb_compression_level = values["rocksdb_compression_level"]
  if "rocksdb_bottommost_compression_level" in values:
    result.rocksdb_bottommost_compression_level = values["rocksdb_bottommost_compression_level"]
  if "rocksdb_bottommost_compression" in values:
    result.rocksdb_bottommost_compression = values["rocksdb_bottommost_compression"]
  if "rocksdb_recovery_mode" in values:
    result.rocksdb_recovery_mode = values["rocksdb_recovery_mode"]
  if "rocksdb_paranoid_file_checks" in values:
    result.rocksdb_paranoid_file_checks = values["rocksdb_paranoid_file_checks"]
  if "rocksdb_checksums" in values:
    result.rocksdb_checksums = values["rocksdb_checksums"]
  if "rocksdb_atomic_flush" in values:
    result.rocksdb_atomic_flush = values["rocksdb_atomic_flush"]
  if "rocksdb_repair" in values:
    result.rocksdb_repair = values["rocksdb_repair"]
  if "rocksdb_read_only" in values:
    result.rocksdb_read_only = values["rocksdb_read_only"]
  if "rocksdb_secondary" in values:
    result.rocksdb_secondary = values["rocksdb_secondary"]
  if "rocksdb_compaction_prio_idle" in values:
    result.rocksdb_compaction_prio_idle = values["rocksdb_compaction_prio_idle"]
  if "rocksdb_compaction_ioprio_idle" in values:
    result.rocksdb_compaction_ioprio_idle = values["rocksdb_compaction_ioprio_idle"]
  if "rocksdb_compaction" in values:
    result.rocksdb_compaction = values["rocksdb_compaction"]
  if "rocksdb_stats_level" in values:
    result.rocksdb_stats_level = values["rocksdb_stats_level"]
  if "rocksdb_never_drop_columns" in values:
    result.rocksdb_never_drop_columns = values["rocksdb_never_drop_columns"]
  if "emergency_password" in values:
    result.emergency_password = values["emergency_password"]
  if "notification_push_path" in values:
    result.notification_push_path = values["notification_push_path"]
  if "push_everything" in values:
    result.push_everything = values["push_everything"]
  if "calculate_heroes" in values:
    result.calculate_heroes = values["calculate_heroes"]
  if "allow_local_presence" in values:
    result.allow_local_presence = values["allow_local_presence"]
  if "allow_incoming_presence" in values:
    result.allow_incoming_presence = values["allow_incoming_presence"]
  if "allow_outgoing_presence" in values:
    result.allow_outgoing_presence = values["allow_outgoing_presence"]
  if "presence_idle_timeout_s" in values:
    result.presence_idle_timeout_s = values["presence_idle_timeout_s"]
  if "presence_offline_timeout_s" in values:
    result.presence_offline_timeout_s = values["presence_offline_timeout_s"]
  if "presence_timeout_remote_users" in values:
    result.presence_timeout_remote_users = values["presence_timeout_remote_users"]
  if "suppress_push_when_active" in values:
    result.suppress_push_when_active = values["suppress_push_when_active"]
  if "allow_incoming_read_receipts" in values:
    result.allow_incoming_read_receipts = values["allow_incoming_read_receipts"]
  if "allow_outgoing_read_receipts" in values:
    result.allow_outgoing_read_receipts = values["allow_outgoing_read_receipts"]
  if "allow_outgoing_typing" in values:
    result.allow_outgoing_typing = values["allow_outgoing_typing"]
  if "allow_incoming_typing" in values:
    result.allow_incoming_typing = values["allow_incoming_typing"]
  if "typing_federation_timeout_s" in values:
    result.typing_federation_timeout_s = values["typing_federation_timeout_s"]
  if "typing_client_timeout_min_s" in values:
    result.typing_client_timeout_min_s = values["typing_client_timeout_min_s"]
  if "typing_client_timeout_max_s" in values:
    result.typing_client_timeout_max_s = values["typing_client_timeout_max_s"]
  if "zstd_compression" in values:
    result.zstd_compression = values["zstd_compression"]
  if "gzip_compression" in values:
    result.gzip_compression = values["gzip_compression"]
  if "brotli_compression" in values:
    result.brotli_compression = values["brotli_compression"]
  if "allow_guest_registration" in values:
    result.allow_guest_registration = values["allow_guest_registration"]
  if "log_guest_registrations" in values:
    result.log_guest_registrations = values["log_guest_registrations"]
  if "allow_guests_auto_join_rooms" in values:
    result.allow_guests_auto_join_rooms = values["allow_guests_auto_join_rooms"]
  if "allow_legacy_media" in values:
    result.allow_legacy_media = values["allow_legacy_media"]
  if "request_legacy_media" in values:
    result.request_legacy_media = values["request_legacy_media"]
  if "freeze_legacy_media" in values:
    result.freeze_legacy_media = values["freeze_legacy_media"]
  if "media_startup_check" in values:
    result.media_startup_check = values["media_startup_check"]
  if "media_compat_file_link" in values:
    result.media_compat_file_link = values["media_compat_file_link"]
  if "prune_missing_media" in values:
    result.prune_missing_media = values["prune_missing_media"]
  if "prevent_media_downloads_from" in values:
    result.prevent_media_downloads_from = values["prevent_media_downloads_from"]
  if "forbidden_remote_server_names" in values:
    result.forbidden_remote_server_names = values["forbidden_remote_server_names"]
  if "forbidden_remote_room_directory_server_names" in values:
    result.forbidden_remote_room_directory_server_names = values["forbidden_remote_room_directory_server_names"]
  if "ip_range_denylist" in values:
    result.ip_range_denylist = values["ip_range_denylist"]
  if "url_preview_bound_interface" in values:
    result.url_preview_bound_interface = values["url_preview_bound_interface"]
  if "url_preview_domain_contains_allowlist" in values:
    result.url_preview_domain_contains_allowlist = values["url_preview_domain_contains_allowlist"]
  if "url_preview_domain_explicit_allowlist" in values:
    result.url_preview_domain_explicit_allowlist = values["url_preview_domain_explicit_allowlist"]
  if "url_preview_domain_explicit_denylist" in values:
    result.url_preview_domain_explicit_denylist = values["url_preview_domain_explicit_denylist"]
  if "url_preview_url_contains_allowlist" in values:
    result.url_preview_url_contains_allowlist = values["url_preview_url_contains_allowlist"]
  if "url_preview_max_spider_size" in values:
    result.url_preview_max_spider_size = values["url_preview_max_spider_size"]
  if "url_preview_check_root_domain" in values:
    result.url_preview_check_root_domain = values["url_preview_check_root_domain"]
  if "forbidden_alias_names" in values:
    result.forbidden_alias_names = values["forbidden_alias_names"]
  if "forbidden_usernames" in values:
    result.forbidden_usernames = values["forbidden_usernames"]
  if "deprioritize_joins_through_servers" in values:
    result.deprioritize_joins_through_servers = values["deprioritize_joins_through_servers"]
  if "max_make_join_attempts_per_join_attempt" in values:
    result.max_make_join_attempts_per_join_attempt = values["max_make_join_attempts_per_join_attempt"]
  if "max_join_attempts_per_join_request" in values:
    result.max_join_attempts_per_join_request = values["max_join_attempts_per_join_request"]
  if "startup_netburst" in values:
    result.startup_netburst = values["startup_netburst"]
  if "startup_netburst_keep" in values:
    result.startup_netburst_keep = values["startup_netburst_keep"]
  if "block_non_admin_invites" in values:
    result.block_non_admin_invites = values["block_non_admin_invites"]
  if "admin_escape_commands" in values:
    result.admin_escape_commands = values["admin_escape_commands"]
  if "admin_console_automatic" in values:
    result.admin_console_automatic = values["admin_console_automatic"]
  if "admin_execute" in values:
    result.admin_execute = values["admin_execute"]
  if "admin_execute_errors_ignore" in values:
    result.admin_execute_errors_ignore = values["admin_execute_errors_ignore"]
  if "admin_signal_execute" in values:
    result.admin_signal_execute = values["admin_signal_execute"]
  if "admin_log_capture" in values:
    result.admin_log_capture = values["admin_log_capture"]
  if "admin_room_tag" in values:
    result.admin_room_tag = values["admin_room_tag"]
  if "grant_admin_to_first_user" in values:
    result.grant_admin_to_first_user = values["grant_admin_to_first_user"]
  if "create_admin_room" in values:
    result.create_admin_room = values["create_admin_room"]
  if "federate_admin_room" in values:
    result.federate_admin_room = values["federate_admin_room"]
  if "sentry" in values:
    result.sentry = values["sentry"]
  if "sentry_endpoint" in values:
    result.sentry_endpoint = values["sentry_endpoint"]
  if "sentry_send_server_name" in values:
    result.sentry_send_server_name = values["sentry_send_server_name"]
  if "sentry_traces_sample_rate" in values:
    result.sentry_traces_sample_rate = values["sentry_traces_sample_rate"]
  if "sentry_attach_stacktrace" in values:
    result.sentry_attach_stacktrace = values["sentry_attach_stacktrace"]
  if "sentry_send_panic" in values:
    result.sentry_send_panic = values["sentry_send_panic"]
  if "sentry_send_error" in values:
    result.sentry_send_error = values["sentry_send_error"]
  if "sentry_filter" in values:
    result.sentry_filter = values["sentry_filter"]
  if "tokio_console" in values:
    result.tokio_console = values["tokio_console"]
  if "test" in values:
    result.test = values["test"]
  if "admin_room_notices" in values:
    result.admin_room_notices = values["admin_room_notices"]
  if "save_unredacted_events" in values:
    result.save_unredacted_events = values["save_unredacted_events"]
  if "redaction_retention_seconds" in values:
    result.redaction_retention_seconds = values["redaction_retention_seconds"]
  if "allow_room_admins_to_request_unredacted_events" in values:
    result.allow_room_admins_to_request_unredacted_events = values["allow_room_admins_to_request_unredacted_events"]
  if "db_pool_affinity" in values:
    result.db_pool_affinity = values["db_pool_affinity"]
  if "db_pool_workers" in values:
    result.db_pool_workers = values["db_pool_workers"]
  if "db_pool_workers_limit" in values:
    result.db_pool_workers_limit = values["db_pool_workers_limit"]
  if "db_pool_max_workers" in values:
    result.db_pool_max_workers = values["db_pool_max_workers"]
  if "db_pool_queue_mult" in values:
    result.db_pool_queue_mult = values["db_pool_queue_mult"]
  if "stream_width_default" in values:
    result.stream_width_default = values["stream_width_default"]
  if "stream_width_scale" in values:
    result.stream_width_scale = values["stream_width_scale"]
  if "stream_amplification" in values:
    result.stream_amplification = values["stream_amplification"]
  if "sender_workers" in values:
    result.sender_workers = values["sender_workers"]
  if "listening" in values:
    result.listening = values["listening"]
  if "config_reload_signal" in values:
    result.config_reload_signal = values["config_reload_signal"]
  if "allow_invalid_tls_certificates" in values:
    result.allow_invalid_tls_certificates = values["allow_invalid_tls_certificates"]
  if "access_control_allow_origin" in values:
    result.access_control_allow_origin = values["access_control_allow_origin"]
  if "hydra_backports" in values:
    result.hydra_backports = values["hydra_backports"]
  if "delete_rooms_after_leave" in values:
    result.delete_rooms_after_leave = values["delete_rooms_after_leave"]
  if "one_time_key_limit" in values:
    result.one_time_key_limit = values["one_time_key_limit"]
  if "single_sso" in values:
    result.single_sso = values["single_sso"]
  if "sso_custom_providers_page" in values:
    result.sso_custom_providers_page = values["sso_custom_providers_page"]
  if "sso_aware_preferred" in values:
    result.sso_aware_preferred = values["sso_aware_preferred"]
  if "blurhashing" in values:
    result.blurhashing = values["blurhashing"]
  if "ldap" in values:
    result.ldap = values["ldap"]
  if "jwt" in values:
    result.jwt = values["jwt"]
  if "appservice" in values:
    result.appservice = values["appservice"]
  if "identity_provider" in values:
    result.identity_provider = values["identity_provider"]
  if "certs" in values:
    result.certs = values["certs"]
  if "key" in values:
    result.key = values["key"]
  if "dual_protocol" in values:
    result.dual_protocol = values["dual_protocol"]
  if "client" in values:
    result.client = values["client"]
  if "server" in values:
    result.server = values["server"]
  if "support_page" in values:
    result.support_page = values["support_page"]
  if "support_role" in values:
    result.support_role = values["support_role"]
  if "support_email" in values:
    result.support_email = values["support_email"]
  if "support_mxid" in values:
    result.support_mxid = values["support_mxid"]
  if "rtc_transports" in values:
    result.rtc_transports = values["rtc_transports"]
  if "components_x" in values:
    result.components_x = values["components_x"]
  if "components_y" in values:
    result.components_y = values["components_y"]
  if "blurhash_max_raw_size" in values:
    result.blurhash_max_raw_size = values["blurhash_max_raw_size"]
  if "enable" in values:
    result.enable = values["enable"]
  if "uri" in values:
    result.uri = values["uri"]
  if "base_dn" in values:
    result.base_dn = values["base_dn"]
  if "bind_dn" in values:
    result.bind_dn = values["bind_dn"]
  if "bind_password_file" in values:
    result.bind_password_file = values["bind_password_file"]
  if "filter" in values:
    result.filter = values["filter"]
  if "uid_attribute" in values:
    result.uid_attribute = values["uid_attribute"]
  if "mail_attribute" in values:
    result.mail_attribute = values["mail_attribute"]
  if "name_attribute" in values:
    result.name_attribute = values["name_attribute"]
  if "admin_base_dn" in values:
    result.admin_base_dn = values["admin_base_dn"]
  if "admin_filter" in values:
    result.admin_filter = values["admin_filter"]
  if "enable" in values:
    result.enable_2 = values["enable"]
  if "key" in values:
    result.key_2 = values["key"]
  if "format" in values:
    result.format = values["format"]
  if "register_user" in values:
    result.register_user = values["register_user"]
  if "algorithm" in values:
    result.algorithm = values["algorithm"]
  if "audience" in values:
    result.audience = values["audience"]
  if "issuer" in values:
    result.issuer = values["issuer"]
  if "require_exp" in values:
    result.require_exp = values["require_exp"]
  if "require_nbf" in values:
    result.require_nbf = values["require_nbf"]
  if "validate_exp" in values:
    result.validate_exp = values["validate_exp"]
  if "validate_nbf" in values:
    result.validate_nbf = values["validate_nbf"]
  if "validate_signature" in values:
    result.validate_signature = values["validate_signature"]
  if "brand" in values:
    result.brand = values["brand"]
  if "client_id" in values:
    result.client_id = values["client_id"]
  if "client_secret" in values:
    result.client_secret = values["client_secret"]
  if "client_secret_file" in values:
    result.client_secret_file = values["client_secret_file"]
  if "issuer_url" in values:
    result.issuer_url = values["issuer_url"]
  if "callback_url" in values:
    result.callback_url = values["callback_url"]
  if "default" in values:
    result.default = values["default"]
  if "name" in values:
    result.name = values["name"]
  if "icon" in values:
    result.icon = values["icon"]
  if "scope" in values:
    result.scope = values["scope"]
  if "userid_claims" in values:
    result.userid_claims = values["userid_claims"]
  if "base_path" in values:
    result.base_path = values["base_path"]
  if "discovery_url" in values:
    result.discovery_url = values["discovery_url"]
  if "authorization_url" in values:
    result.authorization_url = values["authorization_url"]
  if "token_url" in values:
    result.token_url = values["token_url"]
  if "revocation_url" in values:
    result.revocation_url = values["revocation_url"]
  if "introspection_url" in values:
    result.introspection_url = values["introspection_url"]
  if "userinfo_url" in values:
    result.userinfo_url = values["userinfo_url"]
  if "discovery" in values:
    result.discovery = values["discovery"]
  if "grant_session_duration" in values:
    result.grant_session_duration = values["grant_session_duration"]
  if "id" in values:
    result.id = values["id"]
  if "url" in values:
    result.url = values["url"]
  if "as_token" in values:
    result.as_token = values["as_token"]
  if "hs_token" in values:
    result.hs_token = values["hs_token"]
  if "sender_localpart" in values:
    result.sender_localpart = values["sender_localpart"]
  if "users" in values:
    result.users = values["users"]
  if "aliases" in values:
    result.aliases = values["aliases"]
  if "rooms" in values:
    result.rooms = values["rooms"]
  if "rate_limited" in values:
    result.rate_limited = values["rate_limited"]
  if "protocols" in values:
    result.protocols = values["protocols"]
  if "receive_ephemeral" in values:
    result.receive_ephemeral = values["receive_ephemeral"]
  if "device_management" in values:
    result.device_management = values["device_management"]
  if "exclusive" in values:
    result.exclusive = values["exclusive"]
  if "regex" in values:
    result.regex = values["regex"]

let ConfigModelKeys*: seq[string] = @[
  "server_name",
  "database_path",
  "new_user_displayname_suffix",
  "tls",
  "unix_socket_path",
  "unix_socket_perms",
  "database_backup_path",
  "database_backups_to_keep",
  "cache_capacity_modifier",
  "db_cache_capacity_mb",
  "db_write_buffer_capacity_mb",
  "pdu_cache_capacity",
  "auth_chain_cache_capacity",
  "shorteventid_cache_capacity",
  "eventidshort_cache_capacity",
  "eventid_pdu_cache_capacity",
  "shortstatekey_cache_capacity",
  "statekeyshort_cache_capacity",
  "servernameevent_data_cache_capacity",
  "stateinfo_cache_capacity",
  "roomid_spacehierarchy_cache_capacity",
  "client_sync_timeout_min",
  "client_sync_timeout_default",
  "client_sync_timeout_max",
  "dns_cache_entries",
  "dns_min_ttl",
  "dns_min_ttl_nxdomain",
  "dns_attempts",
  "dns_timeout",
  "dns_tcp_fallback",
  "query_all_nameservers",
  "query_over_tcp_only",
  "ip_lookup_strategy",
  "dns_passthru_domains",
  "dns_passthru_appservices",
  "dns_case_randomization",
  "max_request_size",
  "max_fetch_prev_events",
  "request_conn_timeout",
  "request_timeout",
  "request_total_timeout",
  "request_idle_timeout",
  "request_idle_per_host",
  "well_known_conn_timeout",
  "well_known_timeout",
  "federation_timeout",
  "federation_idle_timeout",
  "federation_idle_per_host",
  "sender_timeout",
  "sender_idle_timeout",
  "sender_retry_backoff_limit",
  "appservice_timeout",
  "appservice_idle_timeout",
  "pusher_idle_timeout",
  "client_receive_timeout",
  "client_request_timeout",
  "client_response_timeout",
  "client_shutdown_timeout",
  "sender_shutdown_timeout",
  "allow_registration",
  "yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse",
  "registration_token",
  "registration_token_file",
  "allow_encryption",
  "encryption_enabled_by_default_for_room_type",
  "allow_federation",
  "federate_created_rooms",
  "federation_loopback",
  "forget_forced_upon_leave",
  "require_auth_for_profile_requests",
  "allow_public_room_directory_over_federation",
  "allow_public_room_directory_without_auth",
  "allow_public_room_search_by_id",
  "allow_unlisted_room_search_by_id",
  "show_all_local_users_in_user_directory",
  "turn_allow_guests",
  "lockdown_public_room_directory",
  "allow_device_name_federation",
  "allow_inbound_profile_lookup_federation_requests",
  "allow_room_creation",
  "allow_unstable_room_versions",
  "allow_experimental_room_versions",
  "default_room_version",
  "well_known",
  "allow_jaeger",
  "jaeger_filter",
  "tracing_flame",
  "tracing_flame_filter",
  "tracing_flame_output_path",
  "proxy",
  "trusted_servers",
  "query_trusted_key_servers_first",
  "query_trusted_key_servers_first_on_join",
  "only_query_trusted_key_servers",
  "trusted_server_batch_size",
  "log",
  "log_colors",
  "log_compact",
  "log_span_events",
  "log_filter_regex",
  "log_thread_ids",
  "log_to_stderr",
  "log_enable",
  "log_global_default",
  "openid_token_ttl",
  "login_via_existing_session",
  "login_via_token",
  "login_token_ttl",
  "access_token_ttl",
  "turn_username",
  "turn_password",
  "turn_uris",
  "turn_secret",
  "turn_secret_file",
  "turn_ttl",
  "auto_join_rooms",
  "auto_deactivate_banned_room_attempts",
  "rocksdb_log_level",
  "rocksdb_log_stderr",
  "rocksdb_max_log_file_size",
  "rocksdb_log_time_to_roll",
  "rocksdb_optimize_for_spinning_disks",
  "rocksdb_direct_io",
  "rocksdb_parallelism_threads",
  "rocksdb_max_log_files",
  "rocksdb_compression_algo",
  "rocksdb_compression_level",
  "rocksdb_bottommost_compression_level",
  "rocksdb_bottommost_compression",
  "rocksdb_recovery_mode",
  "rocksdb_paranoid_file_checks",
  "rocksdb_checksums",
  "rocksdb_atomic_flush",
  "rocksdb_repair",
  "rocksdb_read_only",
  "rocksdb_secondary",
  "rocksdb_compaction_prio_idle",
  "rocksdb_compaction_ioprio_idle",
  "rocksdb_compaction",
  "rocksdb_stats_level",
  "rocksdb_never_drop_columns",
  "emergency_password",
  "notification_push_path",
  "push_everything",
  "calculate_heroes",
  "allow_local_presence",
  "allow_incoming_presence",
  "allow_outgoing_presence",
  "presence_idle_timeout_s",
  "presence_offline_timeout_s",
  "presence_timeout_remote_users",
  "suppress_push_when_active",
  "allow_incoming_read_receipts",
  "allow_outgoing_read_receipts",
  "allow_outgoing_typing",
  "allow_incoming_typing",
  "typing_federation_timeout_s",
  "typing_client_timeout_min_s",
  "typing_client_timeout_max_s",
  "zstd_compression",
  "gzip_compression",
  "brotli_compression",
  "allow_guest_registration",
  "log_guest_registrations",
  "allow_guests_auto_join_rooms",
  "allow_legacy_media",
  "request_legacy_media",
  "freeze_legacy_media",
  "media_startup_check",
  "media_compat_file_link",
  "prune_missing_media",
  "prevent_media_downloads_from",
  "forbidden_remote_server_names",
  "forbidden_remote_room_directory_server_names",
  "ip_range_denylist",
  "url_preview_bound_interface",
  "url_preview_domain_contains_allowlist",
  "url_preview_domain_explicit_allowlist",
  "url_preview_domain_explicit_denylist",
  "url_preview_url_contains_allowlist",
  "url_preview_max_spider_size",
  "url_preview_check_root_domain",
  "forbidden_alias_names",
  "forbidden_usernames",
  "deprioritize_joins_through_servers",
  "max_make_join_attempts_per_join_attempt",
  "max_join_attempts_per_join_request",
  "startup_netburst",
  "startup_netburst_keep",
  "block_non_admin_invites",
  "admin_escape_commands",
  "admin_console_automatic",
  "admin_execute",
  "admin_execute_errors_ignore",
  "admin_signal_execute",
  "admin_log_capture",
  "admin_room_tag",
  "grant_admin_to_first_user",
  "create_admin_room",
  "federate_admin_room",
  "sentry",
  "sentry_endpoint",
  "sentry_send_server_name",
  "sentry_traces_sample_rate",
  "sentry_attach_stacktrace",
  "sentry_send_panic",
  "sentry_send_error",
  "sentry_filter",
  "tokio_console",
  "test",
  "admin_room_notices",
  "save_unredacted_events",
  "redaction_retention_seconds",
  "allow_room_admins_to_request_unredacted_events",
  "db_pool_affinity",
  "db_pool_workers",
  "db_pool_workers_limit",
  "db_pool_max_workers",
  "db_pool_queue_mult",
  "stream_width_default",
  "stream_width_scale",
  "stream_amplification",
  "sender_workers",
  "listening",
  "config_reload_signal",
  "allow_invalid_tls_certificates",
  "access_control_allow_origin",
  "hydra_backports",
  "delete_rooms_after_leave",
  "one_time_key_limit",
  "single_sso",
  "sso_custom_providers_page",
  "sso_aware_preferred",
  "blurhashing",
  "ldap",
  "jwt",
  "appservice",
  "identity_provider",
  "certs",
  "key",
  "dual_protocol",
  "client",
  "server",
  "support_page",
  "support_role",
  "support_email",
  "support_mxid",
  "rtc_transports",
  "components_x",
  "components_y",
  "blurhash_max_raw_size",
  "enable",
  "uri",
  "base_dn",
  "bind_dn",
  "bind_password_file",
  "filter",
  "uid_attribute",
  "mail_attribute",
  "name_attribute",
  "admin_base_dn",
  "admin_filter",
  "enable",
  "key",
  "format",
  "register_user",
  "algorithm",
  "audience",
  "issuer",
  "require_exp",
  "require_nbf",
  "validate_exp",
  "validate_nbf",
  "validate_signature",
  "brand",
  "client_id",
  "client_secret",
  "client_secret_file",
  "issuer_url",
  "callback_url",
  "default",
  "name",
  "icon",
  "scope",
  "userid_claims",
  "base_path",
  "discovery_url",
  "authorization_url",
  "token_url",
  "revocation_url",
  "introspection_url",
  "userinfo_url",
  "discovery",
  "grant_session_duration",
  "id",
  "url",
  "as_token",
  "hs_token",
  "sender_localpart",
  "users",
  "aliases",
  "rooms",
  "rate_limited",
  "protocols",
  "receive_ephemeral",
  "device_management",
  "exclusive",
  "regex",
]

const ConfigModelKeyCount* = 308
