## Generated by tools/generate_stubs.py. Do not edit manually.

const
  RustPath* = "service/rooms/event_handler/resolve_state.rs"
  RustCrate* = "service"
  GeneratedAt* = "2026-02-06T01:01:57+00:00"
