#!/usr/bin/env python3
"""Generate Nim stubs and constants from extracted parity inventory."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
PARITY = ROOT / "docs" / "parity"
SRC = ROOT / "src"


def load_json(name: str) -> Dict[str, object]:
    return json.loads((PARITY / name).read_text(encoding="utf-8"))


def write_json(path: Path, data: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=False) + "\n", encoding="utf-8")


def nim_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def snake_to_pascal(s: str) -> str:
    parts = [p for p in s.strip("_").split("_") if p]
    if not parts:
        return "Unnamed"
    return "".join(p[:1].upper() + p[1:] for p in parts)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def render_string_seq(name: str, values: List[str]) -> str:
    lines = [f"let {name}*: seq[string] = @["]
    for v in values:
        lines.append(f"  \"{nim_escape(v)}\",")
    lines.append("]")
    return "\n".join(lines)


def generate_route_inventory(routes: Dict[str, object]) -> None:
    client = list(routes["client_ruma_routes"])
    server = list(routes["server_ruma_routes"])
    manual = list(routes["manual_routes"])

    content = "\n".join(
        [
            "## Generated by tools/generate_stubs.py. Do not edit manually.",
            "",
            render_string_seq("ClientRumaRoutes", client),
            "",
            render_string_seq("ServerRumaRoutes", server),
            "",
            render_string_seq("ManualRoutes", manual),
            "",
            "const",
            f"  ClientRumaRouteCount* = {len(client)}",
            f"  ServerRumaRouteCount* = {len(server)}",
            f"  ManualRouteCount* = {len(manual)}",
            f"  TotalRouteCount* = {len(client) + len(server) + len(manual)}",
            "",
        ]
    )

    write(SRC / "api" / "generated_route_inventory.nim", content)


def generate_route_types(routes: Dict[str, object]) -> None:
    client = list(routes["client_ruma_routes"])
    server = list(routes["server_ruma_routes"])

    used = Counter()
    defs: List[Tuple[str, str, str]] = []

    for kind, names in [("Client", client), ("Server", server)]:
        for name in names:
            base = snake_to_pascal(name)
            key = base
            if used[key] > 0:
                base = kind + base
            used[key] += 1
            req = f"{base}Request"
            res = f"{base}Response"
            defs.append((name, req, res))

    lines = [
        "## Generated by tools/generate_stubs.py. Do not edit manually.",
        "",
        "type",
        "  RoutePlaceholder* = object",
        "    routeName*: string",
        "",
    ]

    for _name, req, res in defs:
        lines.append("type")
        lines.append(f"  {req}* = object")
        lines.append("    placeholder*: RoutePlaceholder")
        lines.append(f"  {res}* = object")
        lines.append("    placeholder*: RoutePlaceholder")
        lines.append("")

    for name, req, res in defs:
        handler = name + "_placeholder"
        lines.append(f"proc {handler}*(req: {req}): {res} =")
        lines.append("  discard req")
        lines.append(f"  {res}(placeholder: RoutePlaceholder(routeName: \"{nim_escape(name)}\"))")
        lines.append("")

    write(SRC / "api" / "generated_route_types.nim", "\n".join(lines).rstrip() + "\n")


def generate_config_keys(config: Dict[str, object]) -> None:
    keys = [f["key"] for f in config["fields"]]
    content = "\n".join(
        [
            "## Generated by tools/generate_stubs.py. Do not edit manually.",
            "",
            render_string_seq("ConfigKeys", keys),
            "",
            f"const ConfigKeyCount* = {len(keys)}",
            "",
        ]
    )
    write(SRC / "core" / "generated_config_keys.nim", content)


def generate_db_cfs(db: Dict[str, object]) -> None:
    names = list(db["column_families"])
    content = "\n".join(
        [
            "## Generated by tools/generate_stubs.py. Do not edit manually.",
            "",
            render_string_seq("DatabaseColumnFamilies", names),
            "",
            f"const DatabaseColumnFamilyCount* = {len(names)}",
            "",
        ]
    )
    write(SRC / "database" / "generated_column_families.nim", content)


def generate_db_cf_descriptors(db: Dict[str, object]) -> None:
    descriptors = list(db.get("descriptors", []))
    required = list(db.get("required_column_families", []))

    lines = [
        "## Generated by tools/generate_stubs.py. Do not edit manually.",
        "",
        "type",
        "  DatabaseColumnFamilyDescriptor* = object",
        "    name*: string",
        "    dropped*: bool",
        "    ignored*: bool",
        "",
        "let DatabaseColumnFamilyDescriptors*: seq[DatabaseColumnFamilyDescriptor] = @[",
    ]

    for item in descriptors:
        lines.append(
            "  DatabaseColumnFamilyDescriptor("
            + f"name: \"{nim_escape(item['name'])}\", "
            + f"dropped: {str(bool(item.get('dropped', False))).lower()}, "
            + f"ignored: {str(bool(item.get('ignored', False))).lower()}"
            + "),"
        )

    lines.extend(
        [
            "]",
            "",
            render_string_seq("RequiredDatabaseColumnFamilies", required),
            "",
            f"const DatabaseColumnFamilyDescriptorCount* = {len(descriptors)}",
            f"const RequiredDatabaseColumnFamilyCount* = {len(required)}",
            "",
        ]
    )

    write(SRC / "database" / "generated_column_family_descriptors.nim", "\n".join(lines))


def generate_function_inventory(functions: Dict[str, object]) -> None:
    by_crate = list(functions["by_crate"])

    lines = [
        "## Generated by tools/generate_stubs.py. Do not edit manually.",
        "",
        "type",
        "  CrateFunctionCount* = object",
        "    crate*: string",
        "    functionCount*: int",
        "    fileCount*: int",
        "",
        "let RustCrateFunctionCounts*: seq[CrateFunctionCount] = @[",
    ]

    for item in by_crate:
        lines.append(
            "  CrateFunctionCount("
            + f"crate: \"{nim_escape(item['crate'])}\", "
            + f"functionCount: {int(item['function_count'])}, "
            + f"fileCount: {int(item['file_count'])}"
            + "),"
        )

    lines.extend(
        [
            "]",
            "",
            f"const RustFunctionTotal* = {int(functions['total_functions'])}",
            "",
        ]
    )

    write(SRC / "core" / "generated_function_inventory.nim", "\n".join(lines))


def generate_service_inventory(functions: Dict[str, object]) -> None:
    module_counts = Counter()
    for f in functions["files"]:
        if f["crate"] != "service":
            continue
        parts = f["rust_path"].split("/")
        module = parts[1] if len(parts) > 1 else "service"
        module_counts[module] += int(f["function_count"])

    lines = [
        "## Generated by tools/generate_stubs.py. Do not edit manually.",
        "",
        "type",
        "  ServiceModuleCount* = object",
        "    module*: string",
        "    functionCount*: int",
        "",
        "let ServiceModuleCounts*: seq[ServiceModuleCount] = @[",
    ]

    for module, count in sorted(module_counts.items()):
        lines.append(
            f"  ServiceModuleCount(module: \"{nim_escape(module)}\", functionCount: {int(count)}),"
        )

    lines.extend(
        [
            "]",
            "",
            f"const ServiceModuleCountTotal* = {len(module_counts)}",
            "",
        ]
    )

    write(SRC / "service" / "generated_service_inventory.nim", "\n".join(lines))


def generate_module_scaffold(module_map: Dict[str, object], baseline: Dict[str, object]) -> Dict[str, object]:
    generated_at = baseline.get("baseline", {}).get("generated_at_utc", "baseline-frozen")
    items = list(module_map["items"])
    mapped = len(items)

    for item in items:
        abs_path = ROOT / item["nim_path"]
        if abs_path.exists():
            continue

        content = "\n".join(
            [
                "## Generated by tools/generate_stubs.py. Do not edit manually.",
                "",
                "const",
                f"  RustPath* = \"{nim_escape(item['rust_path'])}\"",
                f"  RustCrate* = \"{nim_escape(item['crate'])}\"",
                f"  GeneratedAt* = \"{nim_escape(generated_at)}\"",
                "",
            ]
        )
        write(abs_path, content)

    missing_paths: List[str] = []
    for item in items:
        nim_path = item["nim_path"]
        if not (ROOT / nim_path).exists():
            missing_paths.append(nim_path)

    present = mapped - len(missing_paths)
    report = {
        "mapped": mapped,
        "present": present,
        "missing": len(missing_paths),
        "missing_paths": sorted(missing_paths),
    }
    write_json(PARITY / "module_coverage.json", report)
    return report


def main() -> int:
    routes = load_json("route_inventory.json")
    config = load_json("config_inventory.json")
    db = load_json("db_cf_inventory.json")
    functions = load_json("rust_function_inventory.json")
    module_map = load_json("module_map.json")
    baseline = load_json("baseline.json")

    generate_route_inventory(routes)
    generate_route_types(routes)
    generate_config_keys(config)
    generate_db_cfs(db)
    generate_db_cf_descriptors(db)
    generate_function_inventory(functions)
    generate_service_inventory(functions)
    coverage = generate_module_scaffold(module_map, baseline)

    print("Generated Nim stubs in src/")
    print(
        "Module scaffold coverage: "
        f"{coverage['present']}/{coverage['mapped']} present, "
        f"{coverage['missing']} missing"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
