#!/usr/bin/env python3
"""Generate missing Nim modules from docs/parity/module_map.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PARITY = ROOT / "docs" / "parity"


def load_json(name: str):
    return json.loads((PARITY / name).read_text(encoding="utf-8"))


def nim_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=False) + "\n", encoding="utf-8")


def main() -> int:
    module_map = load_json("module_map.json")
    baseline = load_json("baseline.json")
    generated_at = baseline.get("baseline", {}).get("generated_at_utc", "baseline-frozen")
    items = list(module_map["items"])

    created = 0
    for item in items:
        abs_path = ROOT / item["nim_path"]
        if abs_path.exists():
            continue

        content = "\n".join(
            [
                "## Generated by tools/generate_module_scaffold.py. Do not edit manually.",
                "",
                "const",
                f"  RustPath* = \"{nim_escape(item['rust_path'])}\"",
                f"  RustCrate* = \"{nim_escape(item['crate'])}\"",
                f"  GeneratedAt* = \"{nim_escape(generated_at)}\"",
                "",
            ]
        )
        write(abs_path, content)
        created += 1

    missing_paths = []
    for item in items:
        if not (ROOT / item["nim_path"]).exists():
            missing_paths.append(item["nim_path"])

    report = {
        "mapped": len(items),
        "present": len(items) - len(missing_paths),
        "missing": len(missing_paths),
        "missing_paths": sorted(missing_paths),
    }
    write_json(PARITY / "module_coverage.json", report)

    print(f"Created {created} scaffold modules")
    print(
        "Coverage "
        f"{report['present']}/{report['mapped']} present, "
        f"{report['missing']} missing"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
