## Generated by tools/generate_stubs.py. Do not edit manually.

const
  RustPath* = "core/matrix/state_res/event_auth/tests/room_power_levels.rs"
  RustCrate* = "core"
  GeneratedAt* = "2026-02-06T01:01:57+00:00"
